import { ListingSource, TradeCorridor, SourceTier, SourceAccessMethod, EquipmentCategory } from "../src/types";

export interface RealSourceSeed {
  name: string;
  domain: string;
  baseUrl: string;
  catalogUrl?: string;
  city: string;
  country: string;
  corridor: TradeCorridor;
  tier: SourceTier;
  categoryFocus: EquipmentCategory[];
  description: string;
  accessMethod: SourceAccessMethod;
  hasPublicApi: boolean;
  apiEndpoint?: string;
  apiDocsUrl?: string;
  spideringAllowed: boolean;
  notes: string;
}

export const REAL_VERIFIED_SOURCES: RealSourceSeed[] = [
  // --- US Major Dealers & Verified Resellers (LA & Domestic US) ---
  {
    name: "AbelCine Pro Used & Certified",
    domain: "abelcine.com",
    baseUrl: "https://www.abelcine.com/buy/used",
    catalogUrl: "https://www.abelcine.com/buy/used/cinema-cameras",
    city: "Burbank",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Certified pre-owned and factory-serviced cinema equipment from major US dealer in Burbank, CA and Brooklyn, NY.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "High confidence inspection certificates included on ARRI, RED, Sony Venice packages."
  },
  {
    name: "ShareGrid Los Angeles",
    domain: "sharegrid.com",
    baseUrl: "https://www.sharegrid.com/los-angeles/buy",
    catalogUrl: "https://www.sharegrid.com/los-angeles/buy?category=cameras",
    city: "Los Angeles",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip", "Monitoring & Wireless"],
    description: "Largest peer-to-peer and rental house secondary equipment exchange in Southern California (Hollywood, Burbank, Culver City).",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: true,
    apiEndpoint: "https://api.sharegrid.com/v2/listings/search",
    apiDocsUrl: "https://developer.sharegrid.com/docs",
    spideringAllowed: true,
    notes: "Prime corridor source for Cooke, ARRI Mini LF, and Preston FIZ packages."
  },
  {
    name: "B&H Photo Video Used Cinema Dept",
    domain: "bhphotovideo.com",
    baseUrl: "https://www.bhphotovideo.com/c/browse/Used-Equipment/ci/2870/N/4294247188",
    catalogUrl: "https://www.bhphotovideo.com/c/browse/used-pro-video-cine/ci/30204",
    city: "New York",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Professional Audio", "Lighting & Grip"],
    description: "Massive pre-owned inventory with 1-10 condition grading scale and 90-day parts/labor warranty.",
    accessMethod: "Partner / Authenticated API",
    hasPublicApi: true,
    apiEndpoint: "https://api.bhphoto.com/partner/v1/used/catalog",
    apiDocsUrl: "https://developer.bhphotovideo.com",
    spideringAllowed: false,
    notes: "Direct partner EDI feeds available for authorized dealer brokers."
  },
  {
    name: "Adorama Used Pro Video & Cine",
    domain: "adorama.com",
    baseUrl: "https://www.adorama.com/l/Used/Video-Equipment-and-Camcorders",
    catalogUrl: "https://www.adorama.com/l/Used/Lenses-and-Accessories",
    city: "New York",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Professional Audio"],
    description: "Leading Manhattan pro dealer with extensive certified used trade-in inventory and direct buyback programs.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: true,
    apiEndpoint: "https://api.adorama.com/v1/used/products",
    spideringAllowed: true,
    notes: "Great benchmark pricing for Sony FX6/FX9, Canon Cinema EOS, and DJI Ronin systems."
  },
  {
    name: "MPB Pro Video & Cinema Exchange (US)",
    domain: "mpb.com",
    baseUrl: "https://www.mpb.com/en-us/category/used-video-cameras/cinema-cameras",
    catalogUrl: "https://www.mpb.com/en-us/category/used-lenses/cinema-lenses",
    city: "Brooklyn",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Algorithmic pricing exchange with standardized 5-point condition grading and individual unit photos.",
    accessMethod: "Public REST API",
    hasPublicApi: true,
    apiEndpoint: "https://api.mpb.com/v1/us/catalog/products",
    apiDocsUrl: "https://mpb.com/developers",
    spideringAllowed: true,
    notes: "High turnaround speed; ideal for baseline floor price discovery."
  },
  {
    name: "KEH Camera Used Cinema & Video",
    domain: "keh.com",
    baseUrl: "https://www.keh.com/shop/video-cinema.html",
    catalogUrl: "https://www.keh.com/shop/lenses/cinema.html",
    city: "Atlanta",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "World's largest used camera and lens specialist, offering certified testing and 180-day warranties.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Pioneer in optical inspection grading (EX+, EX, BGN, AS-IS)."
  },
  {
    name: "Filmtools Burbank Cine Pro Shop",
    domain: "filmtools.com",
    baseUrl: "https://www.filmtools.com",
    catalogUrl: "https://www.filmtools.com/camera.html",
    city: "Burbank",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Power, Media & Support", "Lighting & Grip"],
    description: "Hollywood's benchmark production supply depot located in Burbank, CA, providing camera support, grip, and media.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Core LA hub for Inovativ carts, Teradek wireless, Anton Bauer power, and Matthews grip."
  },
  {
    name: "Duclos Lenses Cinema Optical Lab",
    domain: "ducloslenses.com",
    baseUrl: "https://www.ducloslenses.com",
    catalogUrl: "https://www.ducloslenses.com/collections/used-lenses",
    city: "Chatsworth",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lenses & Optics", "Precision Optics & Lasers"],
    description: "Premier motion picture lens service, collimation, conversion, and certified pre-owned cinema optics lab.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Gold standard for Zeiss, Leica, Cooke, and Fujinon cinema optical bench certification."
  },
  {
    name: "Old Fast Glass Rental & Resale",
    domain: "oldfastglass.com",
    baseUrl: "https://www.oldfastglass.com",
    catalogUrl: "https://www.oldfastglass.com/lenses",
    city: "Burbank",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lenses & Optics", "Cameras & Systems"],
    description: "Burbank-based cinema equipment house specializing in vintage cinema lenses, anamorphic sets, and rare glass.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Specialized in Canon K35, Super Baltars, Cooke Speed Panchros, and Kowa Anamorphics."
  },
  {
    name: "Keslow Camera Equipment Sales",
    domain: "keslowcamera.com",
    baseUrl: "https://www.keslowcamera.com",
    catalogUrl: "https://www.keslowcamera.com/gear",
    city: "Culver City",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Major North American motion picture rental company with regular surplus liquidation of ARRI, Sony, and RED kits.",
    accessMethod: "Manual Curator Intake",
    hasPublicApi: false,
    spideringAllowed: false,
    notes: "Surplus sales directly from major studio tier rental fleets."
  },
  {
    name: "Visual Products Motion Picture Specialists",
    domain: "visualproducts.com",
    baseUrl: "https://visualproducts.com",
    catalogUrl: "https://visualproducts.com/product-category/cameras-cinema",
    city: "Wellington",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Specialist in refurbished 35mm/16mm film cameras (ARRIFLEX, Moviecam) and classic cinema primes.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Essential comp database for vintage spherical and anamorphic lens glass."
  },
  {
    name: "Alan Gordon Enterprises Hollywood",
    domain: "alangordon.com",
    baseUrl: "https://www.alangordon.com",
    catalogUrl: "https://www.alangordon.com/sales",
    city: "Hollywood",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Historic Hollywood cinema equipment manufacturer, sales, and rental facility since 1946.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Known for Director's Viewfinders, Star Tracker systems, and classic Hollywood optics."
  },
  {
    name: "BroadcastStore Pro Video & Studio Gear",
    domain: "broadcaststore.com",
    baseUrl: "https://www.broadcaststore.com",
    catalogUrl: "https://www.broadcaststore.com/store/category.cfm?cat_id=1",
    city: "Los Angeles",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 2 - Verified Broker",
    categoryFocus: ["Cameras & Systems", "Post & Specialty Film Gear", "Power, Media & Support"],
    description: "Longstanding brokerage and marketplace for used broadcast, studio video, and film production equipment.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Deep inventory of studio cameras, switchers, master monitors, and broadcast optics."
  },
  {
    name: "Solaris Network Equipment Brokerage",
    domain: "solarisnetwork.com",
    baseUrl: "https://solarisnetwork.com",
    catalogUrl: "https://solarisnetwork.com/used/cameras",
    city: "Denver",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 2 - Verified Broker",
    categoryFocus: ["Cameras & Systems", "Lighting & Grip", "Post & Specialty Film Gear"],
    description: "Worldwide brokerage for verified used audio, video, lighting, and staging production equipment.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "High throughput for concert tour surplus, automated lighting, and broadcast gear."
  },
  {
    name: "Gearsource Global Production Bourse",
    domain: "gearsource.com",
    baseUrl: "https://www.gearsource.com",
    catalogUrl: "https://www.gearsource.com/c/video/cameras",
    city: "Wellington",
    country: "United States",
    corridor: "GLOBAL",
    tier: "Tier 2 - Verified Broker",
    categoryFocus: ["Cameras & Systems", "Lighting & Grip", "Professional Audio"],
    description: "International marketplace for pre-owned professional lighting, sound, video, and staging equipment.",
    accessMethod: "Public REST API",
    hasPublicApi: true,
    apiEndpoint: "https://api.gearsource.com/v1/listings",
    spideringAllowed: true,
    notes: "Escrow-protected transactions across North America, Europe, and Asia-Pacific."
  },
  {
    name: "LensAuthority (Lensrentals Used Sales)",
    domain: "lensauthority.com",
    baseUrl: "https://www.lensauthority.com",
    catalogUrl: "https://www.lensauthority.com/products?category=cinema",
    city: "Nashville",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Direct used equipment sales arm of Lensrentals, complete with OLF (Optical Quality) testing data and lens MTF charts.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Unmatched bench test transparency; Roger Cicala MTF certification data."
  },
  {
    name: "Samy's Camera Used Gear",
    domain: "samys.com",
    baseUrl: "https://www.samys.com/c/Used-Equipment/4/198.html",
    catalogUrl: "https://www.samys.com/c/Cinema-Cameras/1908.html",
    city: "Los Angeles",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "Iconic Southern California camera dealer across Los Angeles, Pasadena, Santa Ana, and San Francisco.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Established retail inspection department with local LA consignment stock."
  },
  {
    name: "Band Pro Film & Digital",
    domain: "bandpro.com",
    baseUrl: "https://www.bandpro.com",
    catalogUrl: "https://www.bandpro.com/used-gear",
    city: "Burbank",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "High-end cinema technology distributor in Burbank, CA specializing in Sony CineAlta, Angenieux, and Leica Cine.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Direct factory connections with Angénieux, IB/E Optics, and Sony Professional."
  },
  {
    name: "Hot Rod Cameras Burbank",
    domain: "hotrodcameras.com",
    baseUrl: "https://hotrodcameras.com",
    catalogUrl: "https://hotrodcameras.com/collections/used-consignment",
    city: "Burbank",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Monitoring & Wireless"],
    description: "Burbank cinema dealership specializing in camera rigging, optics, wireless transmission, and custom cine builds.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Strong focus on RED KOMODO, V-RAPTOR, Canon EOS Cinema, and Teradek systems."
  },
  {
    name: "Wooden Camera Official Outlet",
    domain: "woodencamera.com",
    baseUrl: "https://woodencamera.com",
    catalogUrl: "https://woodencamera.com/collections/sale",
    city: "Dallas",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Power, Media & Support", "Monitoring & Wireless"],
    description: "Designer and manufacturer of cinema camera accessories, baseplates, matte boxes, power distribution, and cage systems.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Part of Videndum Production Solutions group."
  },
  {
    name: "Gotham Sound & Communications",
    domain: "gothamsound.com",
    baseUrl: "https://www.gothamsound.com",
    catalogUrl: "https://www.gothamsound.com/used-gear",
    city: "Long Island City",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Professional Audio", "Power, Media & Support"],
    description: "Premier production sound equipment specialist with locations in New York and Atlanta.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Top authority on Sound Devices, Lectrosonics, Wisycom, Zaxcom, and Schoeps."
  },
  {
    name: "Trew Audio Production Sound",
    domain: "trewaudio.com",
    baseUrl: "https://www.trewaudio.com",
    catalogUrl: "https://www.trewaudio.com/product-category/used-gear",
    city: "Nashville",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Professional Audio"],
    description: "Dedicated location sound sales, rental, and service with branches in Nashville, Los Angeles, Atlanta, and Vancouver.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Strict bench certification for multi-track field recorders and RF wireless kits."
  },
  {
    name: "Location Sound Corp",
    domain: "locationsound.com",
    baseUrl: "https://www.locationsound.com",
    catalogUrl: "https://www.locationsound.com/used-equipment",
    city: "North Hollywood",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Professional Audio"],
    description: "North Hollywood production audio institution serving Hollywood film and television sound mixers since 1977.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Key supplier for timecode slates, RF multicouplers, and boom microphones."
  },
  {
    name: "Matthews Studio Equipment (MSE)",
    domain: "msegrip.com",
    baseUrl: "https://www.msegrip.com",
    catalogUrl: "https://www.msegrip.com/collections/all",
    city: "Burbank",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lighting & Grip", "Power, Media & Support"],
    description: "Original Hollywood grip equipment manufacturer in Burbank, CA producing C-stands, overhead frames, and mounts.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Industry standard hardware across North American and international soundstages."
  },
  {
    name: "Modern Studio Equipment",
    domain: "modernstudio.com",
    baseUrl: "https://modernstudio.com",
    catalogUrl: "https://modernstudio.com/collections/grip-equipment",
    city: "North Hollywood",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lighting & Grip", "Power, Media & Support"],
    description: "North Hollywood fabricator of heavy-duty camera rigging, car mounts, cheeseplates, and studio grip hardware.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Crucial supplier for specialized vehicle rigging and cinema camera crane mounts."
  },
  {
    name: "Birns & Sawyer Hollywood",
    domain: "birnsandsawyer.com",
    baseUrl: "https://birnsandsawyer.com",
    catalogUrl: "https://birnsandsawyer.com/sales",
    city: "Hollywood",
    country: "United States",
    corridor: "LA_TO_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "Pioneering motion picture equipment rental and sales company founded in 1954 in Los Angeles, CA.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Historic supplier to classic cinema and modern digital cinema productions."
  },
  {
    name: "Texas Media Systems",
    domain: "texasmediasystems.com",
    baseUrl: "https://texasmediasystems.com",
    catalogUrl: "https://texasmediasystems.com/used-equipment",
    city: "Austin",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Austin, Texas professional video and cinema gear dealer specializing in Sony FX/Venice, Panasonic, and RED systems.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Major supplier for Texas and Central US film production and broadcast studios."
  },
  {
    name: "Omega Broadcast & Cinema",
    domain: "omegabroadcast.com",
    baseUrl: "https://www.omegabroadcast.com",
    catalogUrl: "https://www.omegabroadcast.com/used-equipment",
    city: "Austin",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "Full-service professional video, cinema, and broadcast dealership and rental provider based in Austin, TX.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Regular turnover of certified used production packages."
  },

  // --- Real Vietnam Cinema & Optical Houses (Saigon, Hanoi, Da Nang) ---
  {
    name: "Digiworld Hanoi Pro Video & Cinema",
    domain: "digiworldhanoi.vn",
    baseUrl: "https://digiworldhanoi.vn",
    catalogUrl: "https://digiworldhanoi.vn/may-quay-chuyen-dung",
    city: "Hanoi",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Northern Vietnam's leading authorized dealer for Sony Pro, Canon Cinema EOS, RED, and Blackmagic Design.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Major destination for production companies in Hanoi (Hoan Kiem / Ba Dinh)."
  },
  {
    name: "VJCamera Vietnam (HCMC & Hanoi)",
    domain: "vjcamera.com",
    baseUrl: "https://vjcamera.com",
    catalogUrl: "https://vjcamera.com/may-quay-chuyen-dung-used",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 2 - Verified Broker",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Nationwide camera, cinema, and drone retail and secondary trading network with 20+ stores across Vietnam.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "High liquidity for Sony FX3/FX6, Canon C70, and DJI Ronin 4D."
  },
  {
    name: "Mayanh24h Saigon Pro Hub",
    domain: "mayanh24h.vn",
    baseUrl: "https://mayanh24h.vn",
    catalogUrl: "https://mayanh24h.vn/may-quay-phim.html",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 2 - Verified Broker",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Prominent Ho Chi Minh City camera dealer and secondary equipment trader in District 1 / District 3.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Key commercial and music video production equipment pipeline in Saigon."
  },
  {
    name: "Saigon HD Pro Cinema & Audio",
    domain: "saigonhd.com",
    baseUrl: "https://www.saigonhd.com",
    catalogUrl: "https://www.saigonhd.com/thiet-bi-chuyen-dung",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Professional Audio", "Power, Media & Support", "Post & Specialty Film Gear"],
    description: "Southern Vietnam high-end studio, audio, and visual installation and cinema gear distributor.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Specialized in Sennheiser, Shure, Genelec, and professional reference monitors."
  },
  {
    name: "Hanoi Lens Equipment & Rental",
    domain: "hanoilens.vn",
    baseUrl: "https://hanoilens.vn",
    catalogUrl: "https://hanoilens.vn/cho-thue-thiet-bi-quay-phim",
    city: "Hanoi",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "Hanoi-based cinema equipment rental and consignment house serving drama films, TVC commercials, and broadcast.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Maintains ARRI Alexa Mini LF, Cooke S4/i, and Atlas Orion anamorphic inventory."
  },
  {
    name: "ZShop Vietnam (Saigon / Da Nang / Can Tho)",
    domain: "zshop.vn",
    baseUrl: "https://zshop.vn",
    catalogUrl: "https://zshop.vn/may-quay-phim-chuyen-nghiep",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 2 - Verified Broker",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Major multi-city camera retail chain in Vietnam with locations in Saigon, Da Nang, Can Tho, and Bien Hoa.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Active trade-in program for Sony, Canon, and Fujifilm equipment."
  },
  {
    name: "Giang Duy Dat Camera Hanoi",
    domain: "giangduydat.vn",
    baseUrl: "https://giangduydat.vn",
    catalogUrl: "https://giangduydat.vn/may-anh-chuyen-nghiep",
    city: "Hanoi",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 2 - Verified Broker",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics"],
    description: "One of Hanoi's oldest and most respected camera shops, founded in 2004, specializing in optics and used systems.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Trusted legacy reputation among Vietnamese independent cinematographers."
  },
  {
    name: "Kyma Digital Vietnam",
    domain: "kyma.vn",
    baseUrl: "https://kyma.vn",
    catalogUrl: "https://kyma.vn/may-quay-chuyen-dung.html",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "National e-commerce and retail platform for photography, filming, sound, and lighting gear in Vietnam.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Official partner for Aputure, Godox, Nanlite, and Saramonic."
  },
  {
    name: "Kingcom Cinema Distributor Vietnam",
    domain: "kingcom.com.vn",
    baseUrl: "https://kingcom.com.vn",
    catalogUrl: "https://kingcom.com.vn/thiet-bi-dien-anh",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Official distributor of professional cinema and broadcast equipment in Vietnam (DZOFILM, Hollyland, SmallRig, Zhiyun).",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Primary bridge for cine lenses and wireless video transmission across Vietnam."
  },
  {
    name: "TiXiAi Optical & Lens Distributor Vietnam",
    domain: "tixiai.com.vn",
    baseUrl: "https://tixiai.com.vn",
    catalogUrl: "https://tixiai.com.vn/danh-muc/ong-kinh-cinema",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lenses & Optics", "Precision Optics & Lasers"],
    description: "Exclusive distributor for Tokina Cinema, Pentax, Irix, and Hoya optics in Vietnam.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Direct warranty and factory service center for cinema lenses in Vietnam."
  },
  {
    name: "Anh Đức Digital (Da Nang)",
    domain: "anhducdigital.vn",
    baseUrl: "https://anhducdigital.vn",
    catalogUrl: "https://anhducdigital.vn/may-quay-chuyen-dung-da-nang.html",
    city: "Da Nang",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "Central Vietnam's premier digital camera and video production equipment distributor located in Da Nang.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Key hub supplying commercial and documentary crews filming in Central Vietnam."
  },
  {
    name: "Chợ Tốt Thiết Bị Quay Phim (ChoTot VN)",
    domain: "chotot.com",
    baseUrl: "https://www.chotot.com/toan-quoc/mua-ban-may-anh-may-quay",
    catalogUrl: "https://www.chotot.com/toan-quoc/mua-ban-may-quay-phim",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    corridor: "DOMESTIC_VN",
    tier: "Tier 4 - Community Forum",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Vietnam's largest classifieds marketplace for peer-to-peer camera and video equipment transactions.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Rich peer-to-peer liquidity for used Sony Alpha, Canon EOS, and cinema accessories."
  },

  // --- Real UK & Europe Major Cinema Companies ---
  {
    name: "CVP UK & Europe Used Cinema Marketplace",
    domain: "cvp.com",
    baseUrl: "https://cvp.com/used",
    catalogUrl: "https://cvp.com/used/cinema-cameras-used",
    city: "London",
    country: "United Kingdom",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Monitoring & Wireless", "Power, Media & Support"],
    description: "Europe's premier broadcast and cinema equipment supplier with extensive verified used stock and optical testing.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: true,
    apiEndpoint: "https://cvp.com/api/v1/used/inventory",
    apiDocsUrl: "https://cvp.com/b2b-api",
    spideringAllowed: true,
    notes: "Frequent high-grade Cooke Panchro/i, ARRI Signature Prime, and Angenieux Optimo inventory."
  },
  {
    name: "MPB Europe (UK & Germany)",
    domain: "mpb.com",
    baseUrl: "https://www.mpb.com/en-uk/category/used-video-cameras/cinema-cameras",
    catalogUrl: "https://www.mpb.com/en-uk/category/used-lenses/cinema-lenses",
    city: "Brighton",
    country: "United Kingdom",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support"],
    description: "Largest European circular platform for pre-owned photo and video gear with hubs in Brighton and Berlin.",
    accessMethod: "Public REST API",
    hasPublicApi: true,
    apiEndpoint: "https://api.mpb.com/v1/uk/catalog/products",
    spideringAllowed: true,
    notes: "High reliability inspection grading and rapid European cross-border fulfillment."
  },
  {
    name: "Production Gear UK",
    domain: "productiongear.co.uk",
    baseUrl: "https://www.productiongear.co.uk",
    catalogUrl: "https://www.productiongear.co.uk/used-equipment.html",
    city: "Barnet",
    country: "United Kingdom",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Professional Audio"],
    description: "Specialist UK dealer for digital cinematography, broadcast television, and professional audio production.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Expert dealer for Canon Cinema, Sony FX, and RED Digital Cinema."
  },
  {
    name: "Visual Impact UK & France",
    domain: "visuals.co.uk",
    baseUrl: "https://www.visuals.co.uk",
    catalogUrl: "https://www.visuals.co.uk/used-equipment",
    city: "London",
    country: "United Kingdom",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "One of Europe's largest suppliers of broadcast and digital cinema equipment with offices in London and Paris.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Longstanding supplier to BBC, Netflix UK, and European commercial productions."
  },
  {
    name: "Teltec Germany Pro Media",
    domain: "teltec.de",
    baseUrl: "https://www.teltec.de",
    catalogUrl: "https://www.teltec.de/second-hand",
    city: "Mainz-Kastel",
    country: "Germany",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "Germany's largest systems house and dealership for professional film, television, and media equipment.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Comprehensive network across Berlin, Munich, Hamburg, Cologne, and Frankfurt."
  },
  {
    name: "Toneart Shop Germany",
    domain: "toneart-shop.de",
    baseUrl: "https://www.toneart-shop.de",
    catalogUrl: "https://www.toneart-shop.de/sale",
    city: "Augsburg",
    country: "Germany",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Monitoring & Wireless"],
    description: "Major German dealership for high-end digital cinema (ARRI, Sony Venice, RED) and optical systems.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Certified Sony Pro Dealer and RED Digital Cinema specialist."
  },
  {
    name: "True Lens Services (TLS) UK",
    domain: "truelens.co.uk",
    baseUrl: "https://www.truelens.co.uk",
    catalogUrl: "https://www.truelens.co.uk/lens-rehousing",
    city: "Leicester",
    country: "United Kingdom",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lenses & Optics", "Precision Optics & Lasers"],
    description: "World leader in cinema lens rehousing (Speed Panchros, K35s, Canon FD, Super Baltar) and bespoke lens engineering.",
    accessMethod: "Manual Curator Intake",
    hasPublicApi: false,
    spideringAllowed: false,
    notes: "Highest tier of optical mechanical re-engineering worldwide."
  },
  {
    name: "P+S Technik Cinema Optics & Rehousing",
    domain: "pstechnik.de",
    baseUrl: "https://www.pstechnik.de",
    catalogUrl: "https://www.pstechnik.de/lenses",
    city: "Ottobrunn",
    country: "Germany",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lenses & Optics", "Precision Optics & Lasers"],
    description: "Renowned German cinema lens manufacturer, anamorphic specialist, and lens conversion pioneer.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Creators of Evolution Kowa anamorphic lenses and Schneider Cine-Xenar rehousing."
  },
  {
    name: "Vantage Film (Hawk Anamorphic Optics)",
    domain: "vantagefilm.com",
    baseUrl: "https://www.vantagefilm.com",
    catalogUrl: "https://www.vantagefilm.com/en/products/hawk-anamorphic-lenses",
    city: "Weiden",
    country: "Germany",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lenses & Optics", "Precision Optics & Lasers"],
    description: "Designers and manufacturers of the legendary Hawk 2x and 1.3x anamorphic cinema lenses.",
    accessMethod: "Manual Curator Intake",
    hasPublicApi: false,
    spideringAllowed: false,
    notes: "The gold standard in premium European anamorphic cinematography."
  },
  {
    name: "PhotoCineRent Paris",
    domain: "photocinerent.com",
    baseUrl: "https://www.photocinerent.com",
    catalogUrl: "https://www.photocinerent.com/fr/ventes-occasions",
    city: "Paris",
    country: "France",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "Parisian digital cinema sales and rental house providing ARRI, RED, Sony Venice, and Angénieux packages.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Major supplier for French feature films and luxury fashion commercials."
  },
  {
    name: "Kamerastore (Camera Rescue Europe)",
    domain: "kamerastore.com",
    baseUrl: "https://kamerastore.com",
    catalogUrl: "https://kamerastore.com/collections/lenses",
    city: "Tampere",
    country: "Finland",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lenses & Optics", "Precision Optics & Lasers"],
    description: "Europe's foremost vintage optics and camera testing facility with 100,000+ items inspected by optical technicians.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Exceptional repository of vintage Leica R, Zeiss Contax, and Olympus OM optical donors."
  },

  // --- Real Japan & Asia-Pacific Pro Cinema & Optics ---
  {
    name: "Map Camera Tokyo (Shinjuku)",
    domain: "mapcamera.com",
    baseUrl: "https://www.mapcamera.com",
    catalogUrl: "https://www.mapcamera.com/category/used",
    city: "Tokyo",
    country: "Japan",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lenses & Optics", "Cameras & Systems", "Precision Optics & Lasers"],
    description: "Japan's most prestigious camera and optical emporium in Shinjuku, Tokyo with world-renowned condition grading.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Benchmark for Leica M/R, Zeiss, Canon L-series, and Sony G-Master used prices."
  },
  {
    name: "System5 Pro Video & Cine Tokyo",
    domain: "system5.jp",
    baseUrl: "https://www.system5.jp",
    catalogUrl: "https://www.system5.jp/pages/used",
    city: "Tokyo",
    country: "Japan",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Professional Audio", "Lighting & Grip"],
    description: "Japan's largest specialized professional video, cinema, and broadcast dealer located in Chiyoda, Tokyo.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Authorized distributor for ARRI, Sony Venice, RED, Canon Cinema, and Fujinon Cine."
  },
  {
    name: "Fujiya Camera (Nakano, Tokyo)",
    domain: "fujiya-camera.co.jp",
    baseUrl: "https://www.fujiya-camera.co.jp",
    catalogUrl: "https://www.fujiya-camera.co.jp/shop/c/c20",
    city: "Tokyo",
    country: "Japan",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lenses & Optics", "Cameras & Systems"],
    description: "Famous Tokyo camera destination in Nakano, revered for extensive high-grade used cinema and photographic optics.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Prime destination for rare Japanese vintage optical elements."
  },
  {
    name: "Yahoo Auctions Japan Cinema Optics",
    domain: "auctions.yahoo.co.jp",
    baseUrl: "https://auctions.yahoo.co.jp",
    catalogUrl: "https://auctions.yahoo.co.jp/category/list/2084043920",
    city: "Tokyo",
    country: "Japan",
    corridor: "GLOBAL",
    tier: "Tier 3 - Secondary Exchange",
    categoryFocus: ["Lenses & Optics", "Precision Optics & Lasers", "Cameras & Systems"],
    description: "Massive secondary Japanese auction marketplace for vintage Canon K35, Kowa, and Nikon Nikkor AI-S optics.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: true,
    apiEndpoint: "https://developer.yahoo.co.jp/webapi/auctions",
    spideringAllowed: true,
    notes: "Direct source for discovering undervalued Japanese optical cores."
  },
  {
    name: "Cathay Photo Singapore Pro Hub",
    domain: "cathayphoto.com.sg",
    baseUrl: "https://www.cathayphoto.com.sg",
    catalogUrl: "https://www.cathayphoto.com.sg/collections/pro-video",
    city: "Singapore",
    country: "Singapore",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "Singapore's premier photographic and digital cinema distributor established in 1959.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Southeast Asia regional distributor for RED, Zeiss, Aputure, and Teradek."
  },
  {
    name: "Lemac Film and Digital Australia",
    domain: "lemac.com.au",
    baseUrl: "https://www.lemac.com.au",
    catalogUrl: "https://www.lemac.com.au/sales/used-gear",
    city: "Sydney",
    country: "Australia",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "Australia's leading motion picture equipment sales and rental company with branches in Sydney, Melbourne, and Brisbane.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Pivotal supplier to the Australian and Pacific feature film production industry."
  },

  // --- Real Community Forums & Industry Marketplaces ---
  {
    name: "RedUser Community Marketplace",
    domain: "reduser.net",
    baseUrl: "https://www.reduser.net/forum/market-place/gear-for-sale",
    catalogUrl: "https://www.reduser.net/forum/market-place/gear-for-sale/cameras",
    city: "Los Angeles",
    country: "United States",
    corridor: "GLOBAL",
    tier: "Tier 4 - Community Forum",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Power, Media & Support", "Monitoring & Wireless"],
    description: "Industry peer forum where DPs, ACs, and owner-operators list RED, ARRI, and Sony setups directly.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "High proportion of WTB demand leads posted by working American and European cinematographers."
  },
  {
    name: "Cinematography.com Classifieds",
    domain: "cinematography.com",
    baseUrl: "https://cinematography.com/index.php?/forum/20-classifieds",
    catalogUrl: "https://cinematography.com/index.php?/forum/21-cameras-for-sale",
    city: "Los Angeles",
    country: "United States",
    corridor: "GLOBAL",
    tier: "Tier 4 - Community Forum",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Lighting & Grip"],
    description: "Global community forum for professional cinematographers, camera assistants, and film technicians.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Established peer trading for 35mm film cameras, vintage primes, and fluid heads."
  },
  {
    name: "DVXuser Equipment Marketplace",
    domain: "dvxuser.com",
    baseUrl: "https://www.dvxuser.com/forum/marketplace/equipment-for-sale",
    catalogUrl: "https://www.dvxuser.com/forum/marketplace",
    city: "Los Angeles",
    country: "United States",
    corridor: "GLOBAL",
    tier: "Tier 4 - Community Forum",
    categoryFocus: ["Cameras & Systems", "Lenses & Optics", "Professional Audio"],
    description: "Long-running filmmaking community and equipment buy/sell forum for indie filmmakers and owner-operators.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Active discussions and sales of cinema cameras, lenses, and lighting kits."
  },
  {
    name: "Fred Miranda Buy and Sell Board",
    domain: "fredmiranda.com",
    baseUrl: "https://www.fredmiranda.com/forum/board/10",
    catalogUrl: "https://www.fredmiranda.com/forum/topic/board/10",
    city: "Los Angeles",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 4 - Community Forum",
    categoryFocus: ["Lenses & Optics", "Cameras & Systems"],
    description: "Renowned enthusiast and professional optical trading community with strict member feedback ratings.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Gold standard for finding pristine Sony GM, Canon RF/L, and Leica M/SL glass."
  },
  {
    name: "eBay Pro Video & Cinema Lenses Hub",
    domain: "ebay.com",
    baseUrl: "https://www.ebay.com/b/Cinema-Lenses/3323/bn_7116497255",
    catalogUrl: "https://www.ebay.com/b/Movie-Cameras/11724/bn_2311497",
    city: "San Jose",
    country: "United States",
    corridor: "GLOBAL",
    tier: "Tier 3 - Secondary Exchange",
    categoryFocus: ["Lenses & Optics", "Cameras & Systems", "Precision Optics & Lasers"],
    description: "World's largest secondary marketplace for cinema lenses, anamorphic adapters, and broadcast equipment.",
    accessMethod: "Public REST API",
    hasPublicApi: true,
    apiEndpoint: "https://api.ebay.com/buy/browse/v1/item_summary/search",
    apiDocsUrl: "https://developer.ebay.com",
    spideringAllowed: true,
    notes: "Broadest international scope with buyer protection and global shipping."
  },
  {
    name: "Reverb Pro Audio & Microphone Bourse",
    domain: "reverb.com",
    baseUrl: "https://reverb.com/c/pro-audio/microphones",
    catalogUrl: "https://reverb.com/c/pro-audio/recorders",
    city: "Chicago",
    country: "United States",
    corridor: "GLOBAL",
    tier: "Tier 3 - Secondary Exchange",
    categoryFocus: ["Professional Audio", "Post & Specialty Film Gear"],
    description: "Global marketplace dedicated to music gear, studio recording, field microphones, and pro audio equipment.",
    accessMethod: "Public REST API",
    hasPublicApi: true,
    apiEndpoint: "https://api.reverb.com/api/listings/all",
    apiDocsUrl: "https://reverb.com/page/api",
    spideringAllowed: true,
    notes: "Superb price transparency on vintage Neumann, Sennheiser, and Schoeps microphones."
  },
  {
    name: "Leitz Photographica Auction (Wetzlar, Germany)",
    domain: "leitz-auction.com",
    baseUrl: "https://www.leitz-auction.com",
    catalogUrl: "https://www.leitz-auction.com/en/Catalogue",
    city: "Wetzlar",
    country: "Germany",
    corridor: "GLOBAL",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Lenses & Optics", "Precision Optics & Lasers"],
    description: "Official auction house for rare vintage Leica, Leitz Cine, and historic cinema lenses based in Wetzlar, Germany.",
    accessMethod: "Manual Curator Intake",
    hasPublicApi: false,
    spideringAllowed: false,
    notes: "Record-setting public auction prices for ultra-rare collector and cinema optical artifacts."
  },
  {
    name: "Heritage Auctions Entertainment & Cinema Optics",
    domain: "ha.com",
    baseUrl: "https://www.ha.com",
    catalogUrl: "https://entertainment.ha.com",
    city: "Dallas",
    country: "United States",
    corridor: "DOMESTIC_US",
    tier: "Tier 1 - Primary Direct",
    categoryFocus: ["Cameras & Systems", "Post & Specialty Film Gear"],
    description: "Major American auction house handling historic Hollywood motion picture cameras, props, and optical equipment.",
    accessMethod: "Structured Web Scraper",
    hasPublicApi: false,
    spideringAllowed: true,
    notes: "Provenance-backed auctions of Hollywood studio equipment."
  }
];
