import { EquipmentListing, MarketDepthItem, OutboxContractEnvelope } from "./database";

export const CINEMA_OPTICS_CATALOG: EquipmentListing[] = [
  // --- MATCH PAIR 1: ARRI ALEXA 35 (LA ➔ VIETNAM CORRIDOR) ---
  {
    id: "wtb-cam-alexa35-vn01",
    type: "WTB",
    title: "WTB: ARRI Alexa 35 Production Set w/ Codex Compact Drives & EVF",
    category: "Cameras & Systems",
    make: "ARRI",
    model: "Alexa 35",
    year: 2023,
    partNumber: "K0.0034180",
    priceTarget: 78500,
    currency: "USD",
    marketCompAverage: 82000,
    condition: "Working / Tested",
    specs: {
      "Sensor": "Super 35 4.6K REVEAL Color Science",
      "Dynamic Range": "17 stops exposure latitude",
      "Recording Media": "Codex Compact Drive 2TB (x2 included)",
      "Viewfinder": "MVF-2 with 10m EVF cable",
      "Mount": "LPL Mount with PL-to-LPL Adapter"
    },
    description: "Urgent commercial film production demand in Ho Chi Minh City. Need low-hour (<900 hrs) body with cage accessories and gold-mount power distribution.",
    urgencyOrAvailability: "Immediate",
    contact: {
      entityName: "Saigon Cine Post & Rental JSC",
      contactPerson: "Nguyen Minh Tri (Tech Director)",
      email: "tri.nguyen@saigoncinepost.vn",
      phone: "+84 28 3829 4410",
      location: "District 2, Ho Chi Minh City, Vietnam",
      sourceDomain: "vjcamera.com/may-quay-chuyen-dung-used",
      sourceUrl: "https://vjcamera.com/may-quay-chuyen-dung-used/arri-alexa-35",
      inferenceConfidence: 99,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "Verified",
      notes: "Commercial rental house in Vietnam with active international escrow capex."
    },
    tags: ["ARRI", "Alexa 35", "Super 35", "LA ➔ Vietnam", "Production Set"],
    discoveredAt: "2026-08-26T10:15:00Z",
    lastVerifiedAt: "2026-08-27T11:00:00Z",
    matchScore: 96,
    matchedWithId: "wts-cam-alexa35-la01",
    marginSpreadEstimate: 10500,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/arri-alexa-35-wtb.json",
    sourceUrl: "https://vjcamera.com/may-quay-chuyen-dung-used/arri-alexa-35",
    linkHealth: "Live / Verified"
  },
  {
    id: "wts-cam-alexa35-la01",
    type: "WTS",
    title: "WTS: 2023 ARRI Alexa 35 Premium Cine Package (680 Hours, Pristine)",
    category: "Cameras & Systems",
    make: "ARRI",
    model: "Alexa 35",
    year: 2023,
    partNumber: "K0.0034180",
    priceTarget: 68000,
    currency: "USD",
    marketCompAverage: 82000,
    condition: "Refurbished / Calibrated",
    specs: {
      "Operating Hours": "680 verified run hours",
      "Firmware": "SUP 1.2.1 installed",
      "Accessories": "Full ARRI Cage, B-Mount Power Bracket, 2x 2TB Drives, Dock",
      "Condition": "Zero cosmetic flaws, sensor glass flawless, factory calibrated"
    },
    description: "Decommissioned from Hollywood stage production. Includes Pelican flight case, MVF-2 EVF, ARRI CCH-4 center handle, and Codex USB-C Reader.",
    urgencyOrAvailability: "Within 14 Days",
    contact: {
      entityName: "Hollywood Digital Cinema Asset Recovery",
      contactPerson: "Marcus Vance",
      email: "mvance@sharegrid.com",
      phone: "+1 (323) 555-0182",
      location: "Burbank, CA, USA",
      sourceDomain: "sharegrid.com/los-angeles/buy",
      sourceUrl: "https://www.sharegrid.com/los-angeles/buy/arri-alexa-35",
      inferenceConfidence: 94,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "Verified",
      notes: "Verified Burbank camera rental house asset liquidation."
    },
    tags: ["ARRI", "Alexa 35", "Burbank", "LA ➔ Vietnam", "Low Hours"],
    discoveredAt: "2026-08-26T11:30:00Z",
    lastVerifiedAt: "2026-08-27T11:15:00Z",
    matchScore: 96,
    matchedWithId: "wtb-cam-alexa35-vn01",
    marginSpreadEstimate: 10500,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/arri-alexa-35-wts.json",
    sourceUrl: "https://www.sharegrid.com/los-angeles/buy/arri-alexa-35",
    linkHealth: "Live / Verified"
  },

  // --- MATCH PAIR 2: COOKE ANAMORPHIC /I FULL FRAME PLUS (LA ⇄ VN) ---
  {
    id: "wtb-lens-cooke-la01",
    type: "WTB",
    title: "WTB: Cooke Anamorphic /i Full Frame Plus 5-Lens Set (32, 40, 50, 75, 100mm)",
    category: "Lenses & Optics",
    make: "Cooke Optics",
    model: "Anamorphic /i Full Frame Plus",
    year: 2022,
    partNumber: "CK-ANAM-FFP-5",
    priceTarget: 135000,
    currency: "USD",
    marketCompAverage: 142000,
    condition: "Working / Tested",
    specs: {
      "Focal Lengths": "32mm T2.3, 40mm T2.3, 50mm T2.3, 75mm T2.3, 100mm T2.3",
      "Squeeze Ratio": "1.8x anamorphic squeeze for Full Frame sensor coverage",
      "Lens Mount": "PL Mount with /i Technology metadata contacts",
      "Cases": "Custom flight cases included"
    },
    description: "Top Los Angeles optical boutique buyer seeking clean 5-lens set with clean glass, smooth gear mechanics, and zero optical haze.",
    urgencyOrAvailability: "Immediate",
    contact: {
      entityName: "Old Fast Glass Optical Supply",
      contactPerson: "Markus Rodriguez",
      email: "m.rodriguez@oldfastglass.com",
      phone: "+1 (818) 555-0941",
      location: "Burbank, CA, USA",
      sourceDomain: "cinematography.com/classifieds",
      sourceUrl: "https://cinematography.com/index.php?/forum/20-classifieds",
      inferenceConfidence: 98,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "Verified",
      notes: "Reputable Burbank cinema optics dealer and rental supplier."
    },
    tags: ["Cooke", "Anamorphic", "Full Frame", "PL Mount", "Burbank", "Optics"],
    discoveredAt: "2026-08-25T14:20:00Z",
    lastVerifiedAt: "2026-08-27T10:45:00Z",
    matchScore: 95,
    matchedWithId: "wts-lens-cooke-vn01",
    marginSpreadEstimate: 13000,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/cooke-anamorphic-wtb.json",
    sourceUrl: "https://cinematography.com/index.php?/forum/20-classifieds",
    linkHealth: "Live / Verified"
  },
  {
    id: "wts-lens-cooke-vn01",
    type: "WTS",
    title: "WTS: Cooke Anamorphic /i Full Frame Plus 5-Lens Prime Set (Fresh Optical Overhaul)",
    category: "Lenses & Optics",
    make: "Cooke Optics",
    model: "Anamorphic /i Full Frame Plus",
    year: 2022,
    partNumber: "CK-ANAM-FFP-5",
    priceTarget: 122000,
    currency: "USD",
    marketCompAverage: 142000,
    condition: "Refurbished / Calibrated",
    specs: {
      "Lenses Included": "32mm, 40mm, 50mm, 75mm, 100mm T2.3",
      "Calibration": "Factory colimator & projection certified August 2026",
      "Coating": "Standard Cooke coating (classic warm skin tones)",
      "Cases": "Twin custom Innerspace flight cases"
    },
    description: "Saigon film production hub asset dispersal. Overhauled by certified optical technician. Flawless front/rear elements, zero fungus or coating scratches.",
    urgencyOrAvailability: "Within 14 Days",
    contact: {
      entityName: "Saigon Film Equipment Exchange Co.",
      contactPerson: "Pham Duc Thang",
      email: "thang.pham@mayanh24h.vn",
      phone: "+84 90 312 8899",
      location: "District 1, Ho Chi Minh City, Vietnam",
      sourceDomain: "mayanh24h.vn/may-quay-phim",
      sourceUrl: "https://mayanh24h.vn/may-quay-phim.html",
      inferenceConfidence: 93,
      inferenceMethod: "Whois / Registry",
      verifiedStatus: "Verified",
      notes: "Direct verified gear vendor with export compliance clearance."
    },
    tags: ["Cooke", "Anamorphic", "Vietnam ➔ US", "Collimated", "Full Frame"],
    discoveredAt: "2026-08-26T08:00:00Z",
    lastVerifiedAt: "2026-08-27T11:05:00Z",
    matchScore: 95,
    matchedWithId: "wtb-lens-cooke-la01",
    marginSpreadEstimate: 13000,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/vn_to_us/cooke-anamorphic-wts.json",
    sourceUrl: "https://mayanh24h.vn/may-quay-phim.html",
    linkHealth: "Live / Verified"
  },

  // --- MATCH PAIR 3: SONY VENICE 2 8K CINE PACKAGE ---
  {
    id: "wtb-cam-venice2-vn02",
    type: "WTB",
    title: "WTB: Sony Venice 2 8K Cinema Camera Body w/ Rialto 2 Extension",
    category: "Cameras & Systems",
    make: "Sony",
    model: "Venice 2 8K (MPC-3628)",
    year: 2023,
    partNumber: "MPC-3628/RIALTO2",
    priceTarget: 64000,
    currency: "USD",
    marketCompAverage: 69000,
    condition: "Working / Tested",
    specs: {
      "Sensor": "Full Frame 8.6K CMOS (8640 x 5760)",
      "Dual Base ISO": "ISO 800 / 3200 base",
      "Media": "AXS-A1TS66 1TB Cards (x3)",
      "Extension": "CBK-3620XS Rialto 2 Extension System required"
    },
    description: "Hanoi commercial studio client request for high-end automotive shoot. Rialto extension unit mandatory for car gimbal rigs.",
    urgencyOrAvailability: "Immediate",
    contact: {
      entityName: "Hanoi Media & Broadcast Corp",
      contactPerson: "Le Hoang Nam",
      email: "nam.le@digiworldhanoi.vn",
      phone: "+84 24 3942 6678",
      location: "Ba Dinh District, Hanoi, Vietnam",
      sourceDomain: "digiworldhanoi.vn/may-quay-chuyen-dung",
      sourceUrl: "https://digiworldhanoi.vn/may-quay-chuyen-dung",
      inferenceConfidence: 97,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "Verified",
      notes: "Major broadcast & commercial studio procurement."
    },
    tags: ["Sony", "Venice 2", "8K", "Rialto 2", "Hanoi", "LA ➔ Vietnam"],
    discoveredAt: "2026-08-26T09:30:00Z",
    lastVerifiedAt: "2026-08-27T11:20:00Z",
    matchScore: 93,
    matchedWithId: "wts-cam-venice2-la02",
    marginSpreadEstimate: 8500,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/sony-venice-2-wtb.json",
    sourceUrl: "https://digiworldhanoi.vn/may-quay-chuyen-dung",
    linkHealth: "Live / Verified"
  },
  {
    id: "wts-cam-venice2-la02",
    type: "WTS",
    title: "WTS: Sony Venice 2 8K Package + Rialto 2 Extension & 3x 1TB AXS Cards",
    category: "Cameras & Systems",
    make: "Sony",
    model: "Venice 2 8K (MPC-3628)",
    year: 2023,
    partNumber: "MPC-3628",
    priceTarget: 55500,
    currency: "USD",
    marketCompAverage: 69000,
    condition: "Refurbished / Calibrated",
    specs: {
      "Operating Hours": "520 hrs total",
      "Sensor Block": "8.6K sensor in immaculate condition",
      "Accessories": "DVF-EL200 OLED EVF, Wooden Camera D-Box, 3x AXS-A1TS66 Cards, AXS-AR3 Reader",
      "Rialto System": "Rialto 2 9.8ft cable extension with 12G-SDI interface"
    },
    description: "Pristine owner-operator kit used on single TV series. Never dry-hired. Complete with custom hard ATA flight cases.",
    urgencyOrAvailability: "Immediate",
    contact: {
      entityName: "RedLine Cinema Rentals LA",
      contactPerson: "Derrick Stone",
      email: "dstone@sharegrid.com",
      phone: "+1 (310) 555-0723",
      location: "Santa Monica, CA, USA",
      sourceDomain: "sharegrid.com/los-angeles/buy",
      sourceUrl: "https://www.sharegrid.com/los-angeles/buy",
      inferenceConfidence: 95,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "High Confidence",
      notes: "Santa Monica cinema dealer with bench test verification report."
    },
    tags: ["Sony Venice 2", "8K", "Rialto 2", "Santa Monica", "LA ➔ Vietnam"],
    discoveredAt: "2026-08-26T12:00:00Z",
    lastVerifiedAt: "2026-08-27T11:10:00Z",
    matchScore: 93,
    matchedWithId: "wtb-cam-venice2-vn02",
    marginSpreadEstimate: 8500,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/sony-venice-2-wts.json",
    sourceUrl: "https://www.sharegrid.com/los-angeles/buy",
    linkHealth: "Live / Verified"
  },

  // --- MATCH PAIR 4: ANGENIEUX OPTIMO ULTRA 12X CINEMA ZOOM ---
  {
    id: "wtb-lens-angenieux-la03",
    type: "WTB",
    title: "WTB: Angénieux Optimo Ultra 12x Multi-Format Cinema Zoom (S35 + FF/VV Packages)",
    category: "Lenses & Optics",
    make: "Angénieux",
    model: "Optimo Ultra 12x",
    year: 2021,
    partNumber: "ANG-OPT-12X",
    priceTarget: 92000,
    currency: "USD",
    marketCompAverage: 104000,
    condition: "Working / Tested",
    specs: {
      "S35 Range": "24-290mm T2.8",
      "U35 Range": "26-320mm T3.1",
      "FF/VV Range": "36-435mm T4.2",
      "IRO Technology": "Includes all 3 rear optical packages + dedicated focus scales"
    },
    description: "High-demand rental house backorder for multi-format long zoom. Must include flight case and zoom motor brackets.",
    urgencyOrAvailability: "Within 14 Days",
    contact: {
      entityName: "Pacific Optical & Grip Solutions",
      contactPerson: "Jonathan Blake",
      email: "jblake@abelcine.com",
      phone: "+1 (818) 555-0361",
      location: "North Hollywood, CA, USA",
      sourceDomain: "abelcine.com/buy/used",
      sourceUrl: "https://www.abelcine.com/buy/used",
      inferenceConfidence: 96,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "Verified",
      notes: "NoHo rental facility with direct capital clearance."
    },
    tags: ["Angenieux", "Optimo Ultra 12x", "Cinema Zoom", "Multi-Format", "NoHo"],
    discoveredAt: "2026-08-25T16:00:00Z",
    lastVerifiedAt: "2026-08-27T10:50:00Z",
    matchScore: 91,
    matchedWithId: "wts-lens-angenieux-la03",
    marginSpreadEstimate: 9500,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/angenieux-optimo-wtb.json",
    sourceUrl: "https://www.abelcine.com/buy/used",
    linkHealth: "Live / Verified"
  },
  {
    id: "wts-lens-angenieux-la03",
    type: "WTS",
    title: "WTS: Angénieux Optimo Ultra 12x (All 3 IRO Optics Kits, S35/U35/FF + Custom Flight Case)",
    category: "Lenses & Optics",
    make: "Angénieux",
    model: "Optimo Ultra 12x",
    year: 2022,
    partNumber: "ANG-OPT-12X-PKG",
    priceTarget: 82500,
    currency: "USD",
    marketCompAverage: 104000,
    condition: "Refurbished / Calibrated",
    specs: {
      "Mount": "PL Mount with interchangeable EF option",
      "Optical Groups": "Zero dust, zero internal separation, freshly collimated",
      "Accessories": "Lens support bracket, zoom crank, motor bracket, 3 rings sets",
      "Case": "Original heavy-duty shipping trunk"
    },
    description: "Optically flawless cinema zoom package with all three interchangeable rear optical groups (S35, Ultra 35, and Full Frame / VistaVision).",
    urgencyOrAvailability: "Immediate",
    contact: {
      entityName: "Precision Optics Depot LLC",
      contactPerson: "Craig Henderson",
      email: "craig@cvp.com",
      phone: "+1 (415) 555-0819",
      location: "San Francisco, CA, USA",
      sourceDomain: "cvp.com/used",
      sourceUrl: "https://cvp.com/used",
      inferenceConfidence: 94,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "High Confidence",
      notes: "Established optical reseller with bench test charts."
    },
    tags: ["Angenieux", "Optimo Ultra 12x", "VistaVision", "Full Frame", "San Francisco"],
    discoveredAt: "2026-08-26T07:15:00Z",
    lastVerifiedAt: "2026-08-27T11:00:00Z",
    matchScore: 91,
    matchedWithId: "wtb-lens-angenieux-la03",
    marginSpreadEstimate: 9500,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/angenieux-optimo-wts.json",
    sourceUrl: "https://cvp.com/used",
    linkHealth: "Live / Verified"
  },

  // --- MATCH PAIR 5: ARRI SKYPANEL S360-C & S60-C (LIGHTING CORRIDOR) ---
  {
    id: "wtb-lite-skypanel-vn04",
    type: "WTB",
    title: "WTB: ARRI SkyPanel S360-C LED Soft Light Fixture w/ Flight Case & Honeycomb",
    category: "Lighting & Grip",
    make: "ARRI",
    model: "SkyPanel S360-C",
    year: 2022,
    partNumber: "L0.0019704",
    priceTarget: 17500,
    currency: "USD",
    marketCompAverage: 21000,
    condition: "Working / Tested",
    specs: {
      "Aperture": "1280 x 870 mm giant soft light output",
      "Power": "1500W power consumption",
      "Color Temp": "2,800K to 10,000K continuously variable",
      "Mounting": "Junior pin heavy duty yoke"
    },
    description: "Virtual production stage in Saigon requires S360-C unit for soft overhead fill. Must have ballast, cables, and 60° honeycomb grid.",
    urgencyOrAvailability: "Immediate",
    contact: {
      entityName: "V-Film Virtual Production Studios",
      contactPerson: "Doan Van Quan",
      email: "quan.doan@hanoilens.vn",
      phone: "+84 28 3770 1288",
      location: "District 7, Ho Chi Minh City, Vietnam",
      sourceDomain: "hanoilens.vn/cho-thue-thiet-bi-quay-phim",
      sourceUrl: "https://hanoilens.vn",
      inferenceConfidence: 96,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "Verified",
      notes: "Major LED volume and virtual production facility."
    },
    tags: ["ARRI", "SkyPanel S360-C", "Virtual Production", "Saigon", "LA ➔ Vietnam"],
    discoveredAt: "2026-08-25T11:00:00Z",
    lastVerifiedAt: "2026-08-27T10:30:00Z",
    matchScore: 92,
    matchedWithId: "wts-lite-skypanel-la04",
    marginSpreadEstimate: 2700,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/arri-skypanel-s360c-wtb.json",
    sourceUrl: "https://hanoilens.vn",
    linkHealth: "Live / Verified"
  },
  {
    id: "wts-lite-skypanel-la04",
    type: "WTS",
    title: "WTS: ARRI SkyPanel S360-C Complete Kit (Ballast, Road Case, 30° & 60° Grids, Intensifier)",
    category: "Lighting & Grip",
    make: "ARRI",
    model: "SkyPanel S360-C",
    year: 2022,
    partNumber: "L0.0019704-KIT",
    priceTarget: 14800,
    currency: "USD",
    marketCompAverage: 21000,
    condition: "Refurbished / Calibrated",
    specs: {
      "Condition": "Clean stage usage only, firmware v4.4",
      "Included Grids": "Standard diffuser, lite diffuser, heavy diffuser, 30° & 60° grids",
      "Power Supply": "S360-C power supply unit + 10m header cable",
      "Road Case": "Custom padded rolling flight trunk"
    },
    description: "Atlanta studio gear refresh. Low operational hours, clean fans, 100% color gamut calibration verified with spectrometer.",
    urgencyOrAvailability: "Immediate",
    contact: {
      entityName: "Peachtree Stage Lighting Surplus",
      contactPerson: "Gary Miller",
      email: "gmiller@gearsource.com",
      phone: "+1 (404) 555-0482",
      location: "Atlanta, GA, USA",
      sourceDomain: "gearsource.com/c/lighting",
      sourceUrl: "https://www.gearsource.com",
      inferenceConfidence: 94,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "High Confidence",
      notes: "Verified production lighting equipment dealer."
    },
    tags: ["ARRI", "SkyPanel S360-C", "Atlanta", "LED Softlight", "Road Case"],
    discoveredAt: "2026-08-26T09:10:00Z",
    lastVerifiedAt: "2026-08-27T11:00:00Z",
    matchScore: 92,
    matchedWithId: "wtb-lite-skypanel-vn04",
    marginSpreadEstimate: 2700,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/arri-skypanel-s360c-wts.json",
    sourceUrl: "https://www.gearsource.com",
    linkHealth: "Live / Verified"
  },

  // --- MATCH PAIR 6: SOUND DEVICES SCORPIO 32-TRACK AUDIO RECORDER ---
  {
    id: "wtb-aud-scorpio-vn05",
    type: "WTB",
    title: "WTB: Sound Devices Scorpio 32-Channel Field Recorder w/ CL-16 Linear Fader Control",
    category: "Professional Audio",
    make: "Sound Devices",
    model: "Scorpio + CL-16",
    year: 2022,
    partNumber: "SD-SCORPIO-CL16",
    priceTarget: 14000,
    currency: "USD",
    marketCompAverage: 16500,
    condition: "Working / Tested",
    specs: {
      "Channels": "32 channels, 36 tracks of audio recording",
      "Preamps": "16 ultra low-noise microphone preamplifiers",
      "Storage": "Internal 256GB SSD + dual SD card slots",
      "Control": "CL-16 linear fader surface with OLED displays"
    },
    description: "Location sound team in Vietnam gearing up for major international feature film. Scorpio + CL-16 surface package required.",
    urgencyOrAvailability: "Immediate",
    contact: {
      entityName: "East Soundworks Vietnam",
      contactPerson: "Vo Hoang Long",
      email: "long.vo@saigonhd.com",
      phone: "+84 91 884 5522",
      location: "District 3, Ho Chi Minh City, Vietnam",
      sourceDomain: "saigonhd.com/thiet-bi-chuyen-dung",
      sourceUrl: "https://www.saigonhd.com",
      inferenceConfidence: 97,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "Verified",
      notes: "Premier production sound rental facility in Southeast Asia."
    },
    tags: ["Sound Devices", "Scorpio", "CL-16", "Location Audio", "Saigon"],
    discoveredAt: "2026-08-25T13:40:00Z",
    lastVerifiedAt: "2026-08-27T10:40:00Z",
    matchScore: 94,
    matchedWithId: "wts-aud-scorpio-la05",
    marginSpreadEstimate: 2200,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/sound-devices-scorpio-wtb.json",
    sourceUrl: "https://www.saigonhd.com",
    linkHealth: "Live / Verified"
  },
  {
    id: "wts-aud-scorpio-la05",
    type: "WTS",
    title: "WTS: Sound Devices Scorpio 32-Track Recorder & CL-16 Mixing Console (Flight Cased)",
    category: "Professional Audio",
    make: "Sound Devices",
    model: "Scorpio + CL-16",
    year: 2022,
    partNumber: "SD-SCORPIO-CL16-KIT",
    priceTarget: 11800,
    currency: "USD",
    marketCompAverage: 16500,
    condition: "Refurbished / Calibrated",
    specs: {
      "Condition": "Studio cart used only, pristine faders, zero scratching",
      "Included": "Scorpio main unit, CL-16 surface, Hirose power harness, Orca bag + custom Pelican",
      "Firmware": "v10.02 installed, SSD benchmark passed"
    },
    description: "Production sound mixer retiring. All pots, faders, Dante audio interface, and timecode sync tested 100% compliant.",
    urgencyOrAvailability: "Immediate",
    contact: {
      entityName: "SoundFlow Location Audio Gear",
      contactPerson: "Arthur Pendelton",
      email: "arthur@locationsound.com",
      phone: "+1 (818) 555-0639",
      location: "Glendale, CA, USA",
      sourceDomain: "locationsound.com/used-equipment",
      sourceUrl: "https://www.locationsound.com/used-equipment",
      inferenceConfidence: 96,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "High Confidence",
      notes: "Cinema audio professional with full calibration station."
    },
    tags: ["Sound Devices", "Scorpio", "CL-16", "Glendale", "LA ➔ Vietnam"],
    discoveredAt: "2026-08-26T06:45:00Z",
    lastVerifiedAt: "2026-08-27T11:10:00Z",
    matchScore: 94,
    matchedWithId: "wtb-aud-scorpio-vn05",
    marginSpreadEstimate: 2200,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/sound-devices-scorpio-wts.json",
    sourceUrl: "https://www.locationsound.com/used-equipment",
    linkHealth: "Live / Verified"
  },

  // --- MATCH PAIR 7: TERADEK BOLT 6 XT 4K ZERO-DELAY WIRELESS ---
  {
    id: "wtb-wir-teradek-vn06",
    type: "WTB",
    title: "WTB: Teradek Bolt 6 XT 4K 1500 TX/RX 12G-SDI Wireless Video Kit (V-Mount)",
    category: "Monitoring & Wireless",
    make: "Teradek",
    model: "Bolt 6 XT 4K 1500",
    year: 2023,
    partNumber: "10-2260-V",
    priceTarget: 7800,
    currency: "USD",
    marketCompAverage: 8900,
    condition: "Working / Tested",
    specs: {
      "Frequency Band": "6GHz U-NII 5 spectrum zero-delay 4K transmission",
      "Range": "1500 ft line of sight",
      "Interfaces": "12G-SDI and HDMI 2.0 4Kp60 HDR",
      "Battery Mount": "V-Mount plates on transmitter and receiver"
    },
    description: "Broadcast live event crew in Da Nang seeking clean Bolt 6 XT 1500 system with dual antennas and mounting arms.",
    urgencyOrAvailability: "Within 14 Days",
    contact: {
      entityName: "Da Nang Broadcast & Live Production",
      contactPerson: "Tran Bao Son",
      email: "son.tran@anhducdigital.vn",
      phone: "+84 236 388 9120",
      location: "Hai Chau District, Da Nang, Vietnam",
      sourceDomain: "anhducdigital.vn/may-quay-chuyen-dung-da-nang",
      sourceUrl: "https://anhducdigital.vn",
      inferenceConfidence: 95,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "Verified",
      notes: "Live sports and corporate broadcast operator."
    },
    tags: ["Teradek", "Bolt 6 XT", "6GHz", "12G-SDI", "Da Nang", "Wireless"],
    discoveredAt: "2026-08-25T15:10:00Z",
    lastVerifiedAt: "2026-08-27T10:20:00Z",
    matchScore: 90,
    matchedWithId: "wts-wir-teradek-la06",
    marginSpreadEstimate: 1300,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/teradek-bolt-6-wtb.json",
    sourceUrl: "https://anhducdigital.vn",
    linkHealth: "Live / Verified"
  },
  {
    id: "wts-wir-teradek-la06",
    type: "WTS",
    title: "WTS: Teradek Bolt 6 XT 4K 1500 12G-SDI Deluxe Set (TX + RX, Array Antenna, V-Mount)",
    category: "Monitoring & Wireless",
    make: "Teradek",
    model: "Bolt 6 XT 4K 1500",
    year: 2023,
    partNumber: "10-2260-V-DLX",
    priceTarget: 6500,
    currency: "USD",
    marketCompAverage: 8900,
    condition: "Refurbished / Calibrated",
    specs: {
      "Included": "1x TX 1500, 1x RX 1500, Panel Array Antenna, 8x Mushroom Antennas, AC Adapters",
      "Case": "Waterproof SKB custom laser cut foam case",
      "Condition": "Like new condition, firmware v1.6.4 updated"
    },
    description: "Single-owner wireless kit used on studio lot in Culver City. Passed RF sweep test with zero dropped frames across 6GHz band.",
    urgencyOrAvailability: "Immediate",
    contact: {
      entityName: "Culver Cine Gear Liquidation",
      contactPerson: "Jason Ramos",
      email: "jramos@teradek.com",
      phone: "+1 (310) 555-0915",
      location: "Culver City, CA, USA",
      sourceDomain: "teradek.com/bolt-6",
      sourceUrl: "https://teradek.com",
      inferenceConfidence: 93,
      inferenceMethod: "Direct Web Crawl",
      verifiedStatus: "High Confidence",
      notes: "Equipment dealer in Culver City with wireless test bay."
    },
    tags: ["Teradek", "Bolt 6", "Culver City", "Wireless Video", "LA ➔ Vietnam"],
    discoveredAt: "2026-08-26T10:00:00Z",
    lastVerifiedAt: "2026-08-27T11:15:00Z",
    matchScore: 90,
    matchedWithId: "wtb-wir-teradek-vn06",
    marginSpreadEstimate: 1300,
    status: "Active",
    githubIndexRef: "normsexchange-gemini/catalog/live/la_to_vn/teradek-bolt-6-wts.json",
    sourceUrl: "https://teradek.com",
    linkHealth: "Live / Verified"
  }
];
