import React, { useState } from "react";
import { Norm, AuditResult, ConflictResolution } from "../types";
import { 
  Sparkles, 
  Bot, 
  ShieldAlert, 
  Scale, 
  Zap, 
  CheckCircle2, 
  AlertTriangle, 
  ArrowRight, 
  Send, 
  Plus, 
  RefreshCw, 
  Layers,
  FileSearch,
  MessageSquare,
  Flame,
  Lightbulb,
  Check
} from "lucide-react";

interface AINormsArchitectProps {
  onAdoptNorm: (norm: Norm) => void;
  onPublishNormToExchange: (norm: Norm) => void;
  activeCharterNorms: Norm[];
}

export const AINormsArchitect: React.FC<AINormsArchitectProps> = ({
  onAdoptNorm,
  onPublishNormToExchange,
  activeCharterNorms,
}) => {
  const [subTab, setSubTab] = useState<"generator" | "auditor" | "resolver" | "advisor">("generator");

  // Generator State
  const [teamType, setTeamType] = useState("Distributed Product & Engineering Squad");
  const [context, setContext] = useState("12 people across SF (UTC-7), London (UTC+0), and Tokyo (UTC+9)");
  const [challenges, setChallenges] = useState("Endless Slack notifications, PR reviews blocked for days, meeting fatigue across timezones");
  const [culturePillars, setCulturePillars] = useState("Deep work sanctuary, blameless psychological safety, asynchronous clarity");
  const [generating, setGenerating] = useState(false);
  const [generatedNorms, setGeneratedNorms] = useState<Norm[]>([]);
  const [generatorError, setGeneratorError] = useState<string | null>(null);

  // Auditor State
  const [charterText, setCharterText] = useState(
    activeCharterNorms.length > 0
      ? activeCharterNorms.map((n, i) => `${i + 1}. ${n.title}\nRule: ${n.explicitRule}\nTrigger: ${n.triggerSituation}\nRemedy: ${n.violationRemedy}`).join("\n\n")
      : `1. Core Hours: Everyone is expected to be reachable on Slack between 9 AM and 5 PM.\n2. Meetings: Always show up on time. Cameras should generally be turned on.\n3. Code Reviews: Try to review PRs as soon as you have free time.\n4. Decisions: Decisions are made by the team lead after hearing everyone's input.`
  );
  const [teamSize, setTeamSize] = useState("10-20 people");
  const [workingMode, setWorkingMode] = useState("Global Hybrid & Asynchronous");
  const [auditing, setAuditing] = useState(false);
  const [auditResult, setAuditResult] = useState<AuditResult | null>(null);
  const [auditError, setAuditError] = useState<string | null>(null);

  // Resolver State
  const [normA, setNormA] = useState("Immediate Slack responsiveness for customer and stakeholder escalations.");
  const [normB, setNormB] = useState("Protected 4-hour morning deep work blocks with notifications paused.");
  const [conflictContext, setConflictContext] = useState("Fast-paced SaaS engineering team balancing high bug triage with complex feature builds.");
  const [resolving, setResolving] = useState(false);
  const [conflictResolution, setConflictResolution] = useState<ConflictResolution | null>(null);
  const [resolverError, setResolverError] = useState<string | null>(null);

  // Advisor Chat State
  const [chatMessages, setChatMessages] = useState<Array<{ role: "user" | "architect"; content: string }>>([
    {
      role: "architect",
      content: "Hello! I am your AI Norms Architect. I specialize in Social Exchange Theory, team charters, psychological safety, and eliminating unwritten friction points. What dynamic or tension would you like to formalize into a clear operating norm today?"
    }
  ]);
  const [chatInput, setChatInput] = useState("");
  const [chatLoading, setChatLoading] = useState(false);

  // Handlers
  const handleGenerateNorms = async (e: React.FormEvent) => {
    e.preventDefault();
    setGenerating(true);
    setGeneratorError(null);
    try {
      const res = await fetch("/api/ai/generate-norms", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ teamType, context, challenges, culturePillars }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);

      // Enhance with local metadata
      const formatted: Norm[] = (data.norms || []).map((n: any, idx: number) => ({
        ...n,
        id: `ai-gen-${Date.now()}-${idx}`,
        votesCount: 1,
        adoptionsCount: 1,
        clarityScore: 94,
        isCustom: true,
        isAutoGenerated: true,
        generationMethod: "Gemini 3.7 Flash Engine",
        tags: ["AutoGenerated", "AIGenerated", n.category || "Custom"],
        author: {
          name: "AI Norms Architect",
          role: "Gemini 3.7 Flash Engine",
          avatar: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80",
          organization: "NormsExchange AI"
        }
      }));

      setGeneratedNorms(formatted);
    } catch (err: any) {
      console.error(err);
      setGeneratorError(err.message || "Failed to generate norms. Please verify your GEMINI_API_KEY.");
    } finally {
      setGenerating(false);
    }
  };

  const handleAuditCharter = async (e: React.FormEvent) => {
    e.preventDefault();
    setAuditing(true);
    setAuditError(null);
    try {
      const res = await fetch("/api/ai/audit-charter", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ charterText, teamSize, workingMode }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setAuditResult(data.audit);
    } catch (err: any) {
      console.error(err);
      setAuditError(err.message || "Failed to audit charter.");
    } finally {
      setAuditing(false);
    }
  };

  const handleResolveConflict = async (e: React.FormEvent) => {
    e.preventDefault();
    setResolving(true);
    setResolverError(null);
    try {
      const res = await fetch("/api/ai/resolve-conflict", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ normA, normB, teamContext: conflictContext }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setConflictResolution(data.resolution);
    } catch (err: any) {
      console.error(err);
      setResolverError(err.message || "Failed to resolve norm conflict.");
    } finally {
      setResolving(false);
    }
  };

  const handleSendChatMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim() || chatLoading) return;

    const userText = chatInput.trim();
    const newHistory = [...chatMessages, { role: "user" as const, content: userText }];
    setChatMessages(newHistory);
    setChatInput("");
    setChatLoading(true);

    try {
      const res = await fetch("/api/ai/chat-architect", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: userText,
          conversationHistory: newHistory,
          activeCharter: activeCharterNorms,
        }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);

      setChatMessages((prev) => [
        ...prev,
        { role: "architect", content: data.reply || "I have analyzed your situation and suggest formalizing explicit boundaries." }
      ]);
    } catch (err: any) {
      console.error(err);
      setChatMessages((prev) => [
        ...prev,
        { role: "architect", content: "I encountered an error connecting to the Gemini engine. Please check your network and API key settings." }
      ]);
    } finally {
      setChatLoading(false);
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-200">
      
      {/* Sub-Navigation Header */}
      <div className="glass rounded-2xl p-6 sm:p-8 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse" />
            <span className="text-xs font-mono font-bold uppercase tracking-wider text-emerald-400">
              GEMINI 3.7 FLASH REASONING ENGINE
            </span>
          </div>
          <h2 className="text-xl font-bold text-white">
            AI Norms Architect & Organizational Auditor
          </h2>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl">
            Formulate high-velocity operating agreements, audit unspoken friction, and synthesize cultural gridlocks.
          </p>
        </div>

        {/* SubTab Switcher */}
        <div className="flex flex-wrap items-center gap-1.5 bg-slate-950/80 p-1.5 rounded-xl border border-slate-800">
          <button
            onClick={() => setSubTab("generator")}
            className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              subTab === "generator"
                ? "bg-indigo-600 text-white shadow-md shadow-indigo-500/25"
                : "text-slate-400 hover:text-slate-200"
            }`}
          >
            <Sparkles className="h-3.5 w-3.5" />
            <span>Norm Generator</span>
          </button>

          <button
            onClick={() => setSubTab("auditor")}
            className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              subTab === "auditor"
                ? "bg-indigo-600 text-white shadow-md shadow-indigo-500/25"
                : "text-slate-400 hover:text-slate-200"
            }`}
          >
            <FileSearch className="h-3.5 w-3.5" />
            <span>Charter Auditor</span>
          </button>

          <button
            onClick={() => setSubTab("resolver")}
            className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              subTab === "resolver"
                ? "bg-indigo-600 text-white shadow-md shadow-indigo-500/25"
                : "text-slate-400 hover:text-slate-200"
            }`}
          >
            <Scale className="h-3.5 w-3.5" />
            <span>Conflict Synthesizer</span>
          </button>

          <button
            onClick={() => setSubTab("advisor")}
            className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              subTab === "advisor"
                ? "bg-indigo-600 text-white shadow-md shadow-indigo-500/25"
                : "text-slate-400 hover:text-slate-200"
            }`}
          >
            <MessageSquare className="h-3.5 w-3.5" />
            <span>Live Advisor</span>
          </button>
        </div>
      </div>

      {/* SUB-VIEW 1: NORM GENERATOR */}
      {subTab === "generator" && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Input Config Form */}
          <div className="lg:col-span-5 glass-card p-6 rounded-2xl space-y-4">
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-indigo-400" />
              <span>Configure Team Profile</span>
            </h3>

            <form onSubmit={handleGenerateNorms} className="space-y-4 text-xs">
              <div>
                <label className="font-mono text-[11px] uppercase tracking-wider text-slate-300 block mb-1">
                  Team Domain / Structure
                </label>
                <input
                  type="text"
                  value={teamType}
                  onChange={(e) => setTeamType(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700/80 rounded-xl p-2.5 text-slate-200 focus:border-indigo-500 focus:outline-none"
                  placeholder="e.g. Distributed Core Engineering, International Customs Ops..."
                />
              </div>

              <div>
                <label className="font-mono text-[11px] uppercase tracking-wider text-slate-300 block mb-1">
                  Working Setup & Timezones
                </label>
                <input
                  type="text"
                  value={context}
                  onChange={(e) => setContext(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700/80 rounded-xl p-2.5 text-slate-200 focus:border-indigo-500 focus:outline-none"
                  placeholder="e.g. 10 people across 3 continents..."
                />
              </div>

              <div>
                <label className="font-mono text-[11px] uppercase tracking-wider text-slate-300 block mb-1">
                  Current Pain Points & Hidden Friction
                </label>
                <textarea
                  rows={3}
                  value={challenges}
                  onChange={(e) => setChallenges(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700/80 rounded-xl p-2.5 text-slate-200 focus:border-indigo-500 focus:outline-none"
                  placeholder="e.g. Unclear ownership, PR delays, off-hours pings..."
                />
              </div>

              <div>
                <label className="font-mono text-[11px] uppercase tracking-wider text-slate-300 block mb-1">
                  Desired Cultural Pillars & Principles
                </label>
                <input
                  type="text"
                  value={culturePillars}
                  onChange={(e) => setCulturePillars(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700/80 rounded-xl p-2.5 text-slate-200 focus:border-indigo-500 focus:outline-none"
                  placeholder="e.g. Deep work sanctuary, high reciprocity, psychological safety..."
                />
              </div>

              {generatorError && (
                <div className="p-3 rounded-xl bg-rose-950/60 border border-rose-800 text-rose-300">
                  {generatorError}
                </div>
              )}

              <button
                type="submit"
                disabled={generating}
                className="w-full py-2.5 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-lg shadow-indigo-500/25 transition-all flex items-center justify-center gap-2 disabled:opacity-60"
              >
                {generating ? (
                  <>
                    <RefreshCw className="h-4 w-4 animate-spin" />
                    <span>Architecting Custom Norms...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" />
                    <span>Generate Structured Norms</span>
                  </>
                )}
              </button>
            </form>
          </div>

          {/* Generated Results Column */}
          <div className="lg:col-span-7 space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-base font-bold text-white">
                Architected Norms Output ({generatedNorms.length})
              </h3>
              {generatedNorms.length > 0 && (
                <span className="text-xs font-mono font-medium text-emerald-400">
                  ✓ Ready for Adoption & Minting
                </span>
              )}
            </div>

            {generatedNorms.length === 0 && !generating && (
              <div className="p-12 text-center rounded-2xl glass-card text-slate-400 space-y-3">
                <Lightbulb className="h-8 w-8 text-indigo-400 mx-auto" />
                <p className="text-sm font-medium text-slate-200">
                  No norms generated yet
                </p>
                <p className="text-xs max-w-sm mx-auto text-slate-400">
                  Provide your team's timezone, operational domain, and friction points on the left to generate customized operating rules.
                </p>
              </div>
            )}

            {generating && (
              <div className="p-12 text-center rounded-2xl glass-card text-slate-300 space-y-4">
                <RefreshCw className="h-8 w-8 text-indigo-400 animate-spin mx-auto" />
                <p className="text-sm font-semibold text-white">
                  Synthesizing Social Exchange Contracts with Gemini 3.7 Flash...
                </p>
                <p className="text-xs text-slate-400 max-w-md mx-auto">
                  Analyzing reciprocal equity balances, asynchronous protocols, and blameless remedy formulas.
                </p>
              </div>
            )}

            {generatedNorms.map((norm, index) => (
              <div
                key={norm.id}
                className="p-5 rounded-2xl glass-card space-y-3"
              >
                <div className="flex items-center justify-between gap-2">
                  <span className="text-xs font-mono font-semibold px-2.5 py-0.5 rounded-lg bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                    {norm.category}
                  </span>
                  <span className="text-xs font-mono font-bold text-emerald-400">
                    {norm.reciprocityIndex}% Reciprocity Index
                  </span>
                </div>

                <div>
                  <h4 className="text-base font-bold text-white">
                    {norm.title}
                  </h4>
                  <p className="text-xs text-slate-400 mt-0.5 font-normal">
                    {norm.tagline}
                  </p>
                </div>

                {/* Trigger & Rule */}
                <div className="p-3.5 rounded-xl bg-slate-950/80 border border-slate-800 space-y-2 text-xs">
                  <div>
                    <span className="font-mono font-bold text-amber-400 uppercase tracking-wider text-[10px] block">
                      Trigger:
                    </span>
                    <p className="text-slate-300 text-[11px]">{norm.triggerSituation}</p>
                  </div>
                  <div className="pt-1.5 border-t border-slate-800">
                    <span className="font-mono font-bold text-indigo-300 uppercase tracking-wider text-[10px] block">
                      Explicit Rule:
                    </span>
                    <p className="text-slate-200 font-medium text-[11px]">{norm.explicitRule}</p>
                  </div>
                  <div className="pt-1.5 border-t border-slate-800">
                    <span className="font-mono font-bold text-emerald-400 uppercase tracking-wider text-[10px] block">
                      Blameless Remedy:
                    </span>
                    <p className="text-slate-300 text-[11px]">{norm.violationRemedy}</p>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex items-center justify-end gap-2 pt-1">
                  <button
                    onClick={() => {
                      onPublishNormToExchange(norm);
                    }}
                    className="px-3 py-1.5 rounded-xl bg-slate-800/80 hover:bg-slate-800 text-slate-300 text-xs font-semibold border border-slate-700/80 transition-colors"
                  >
                    Mint to Exchange
                  </button>

                  <button
                    onClick={() => onAdoptNorm(norm)}
                    className="px-3.5 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-md shadow-indigo-500/20 transition-all flex items-center gap-1"
                  >
                    <Plus className="h-3.5 w-3.5" />
                    <span>Adopt to Charter</span>
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SUB-VIEW 2: CHARTER AUDITOR */}
      {subTab === "auditor" && (
        <div className="space-y-6">
          <div className="glass-card p-6 rounded-2xl space-y-4">
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <FileSearch className="h-4 w-4 text-indigo-400" />
              <span>Charter Friction & Blindspot Scanner</span>
            </h3>
            <p className="text-xs text-slate-400">
              Paste your team guidelines, working agreements, or current handbook. The AI will detect ambiguous assumptions, power imbalances, and missing psychological safety guardrails.
            </p>

            <form onSubmit={handleAuditCharter} className="space-y-4 text-xs">
              <div>
                <label className="font-mono text-[11px] uppercase tracking-wider text-slate-300 block mb-1">
                  Charter / Handbook Text
                </label>
                <textarea
                  rows={6}
                  value={charterText}
                  onChange={(e) => setCharterText(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700/80 rounded-xl p-3 text-slate-200 font-mono text-xs focus:border-indigo-500 focus:outline-none"
                  placeholder="Paste your operating rules..."
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="font-mono text-[11px] uppercase tracking-wider text-slate-300 block mb-1">
                    Team Size
                  </label>
                  <input
                    type="text"
                    value={teamSize}
                    onChange={(e) => setTeamSize(e.target.value)}
                    className="w-full bg-slate-900 border border-slate-700/80 rounded-xl p-2.5 text-slate-200 focus:border-indigo-500 focus:outline-none"
                  />
                </div>

                <div>
                  <label className="font-mono text-[11px] uppercase tracking-wider text-slate-300 block mb-1">
                    Working Mode
                  </label>
                  <input
                    type="text"
                    value={workingMode}
                    onChange={(e) => setWorkingMode(e.target.value)}
                    className="w-full bg-slate-900 border border-slate-700/80 rounded-xl p-2.5 text-slate-200 focus:border-indigo-500 focus:outline-none"
                  />
                </div>
              </div>

              {auditError && (
                <div className="p-3 rounded-xl bg-rose-950/60 border border-rose-800 text-rose-300">
                  {auditError}
                </div>
              )}

              <button
                type="submit"
                disabled={auditing}
                className="py-2.5 px-5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-lg shadow-indigo-500/25 transition-all flex items-center justify-center gap-2 disabled:opacity-60"
              >
                {auditing ? (
                  <>
                    <RefreshCw className="h-4 w-4 animate-spin" />
                    <span>Analyzing Charter Dynamics...</span>
                  </>
                ) : (
                  <>
                    <FileSearch className="h-4 w-4" />
                    <span>Run AI Friction Audit</span>
                  </>
                )}
              </button>
            </form>
          </div>

          {/* Audit Results View */}
          {auditResult && (
            <div className="glass-card p-6 sm:p-8 rounded-2xl space-y-6 animate-in fade-in duration-200">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
                <div>
                  <h4 className="text-lg font-bold text-white">
                    Charter Audit & Diagnostics Report
                  </h4>
                  <p className="text-xs text-slate-400 mt-0.5">
                    Evaluated against standard Social Exchange Theory & psychological safety benchmarks.
                  </p>
                </div>

                <div className="flex items-center gap-3">
                  <div className="text-right">
                    <span className="text-xs font-mono font-semibold text-slate-400 block">OVERALL HEALTH</span>
                    <span className="text-2xl font-black font-mono text-emerald-400">
                      {auditResult.overallHealthScore}/100
                    </span>
                  </div>
                </div>
              </div>

              {/* Executive Summary */}
              <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800 text-xs text-slate-300 leading-relaxed">
                <span className="font-mono font-bold text-amber-400 block mb-1 uppercase tracking-wider text-[10px]">
                  Executive Assessment:
                </span>
                {auditResult.executiveSummary}
              </div>

              {/* Metric Breakdown Cards */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800">
                  <span className="text-xs font-mono text-slate-400 block mb-1">CLARITY OF TRIGGERS</span>
                  <span className="text-xl font-mono font-bold text-indigo-400">{auditResult.clarityScore}%</span>
                </div>

                <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800">
                  <span className="text-xs font-mono text-slate-400 block mb-1">RECIPROCITY BALANCE</span>
                  <span className="text-xl font-mono font-bold text-emerald-400">{auditResult.reciprocityScore}%</span>
                </div>

                <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800">
                  <span className="text-xs font-mono text-slate-400 block mb-1">PSYCHOLOGICAL SAFETY</span>
                  <span className="text-xl font-mono font-bold text-indigo-300">{auditResult.psychologicalSafetyScore}%</span>
                </div>
              </div>

              {/* Critical Friction Points & Unwritten Assumptions */}
              <div>
                <h5 className="text-xs font-mono font-bold uppercase tracking-wider text-rose-400 mb-3 flex items-center gap-1.5">
                  <ShieldAlert className="h-4 w-4" />
                  <span>Critical Friction Traps & Unwritten Assumptions</span>
                </h5>

                <div className="space-y-3">
                  {auditResult.criticalFrictionPoints?.map((item, idx) => (
                    <div
                      key={idx}
                      className="p-4 rounded-xl bg-rose-950/20 border border-rose-900/40 text-xs space-y-2"
                    >
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-rose-300 text-sm">
                          {item.risk}
                        </span>
                        <span className="text-[10px] font-mono font-semibold px-2 py-0.5 rounded-md bg-rose-900/60 text-rose-200">
                          {item.impact} Impact
                        </span>
                      </div>
                      <p className="text-slate-300 text-[11px]">
                        <strong className="text-amber-300">Hidden Assumption:</strong> {item.unwrittenAssumption}
                      </p>
                      <p className="text-emerald-300 bg-slate-950/80 p-3 rounded-lg border border-slate-800 text-[11px]">
                        <strong className="text-emerald-400">Recommended Patch:</strong> {item.recommendedPatch}
                      </p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Missing Crucial Norms */}
              {auditResult.missingCrucialNorms && auditResult.missingCrucialNorms.length > 0 && (
                <div className="p-4 rounded-xl bg-amber-950/20 border border-amber-900/40 text-xs">
                  <span className="font-mono font-bold text-amber-300 block mb-2 text-[11px] uppercase tracking-wider">
                    ⚠️ Missing Core Norms Recommended for this Team:
                  </span>
                  <div className="flex flex-wrap gap-2">
                    {auditResult.missingCrucialNorms.map((name, i) => (
                      <span
                        key={i}
                        className="px-2.5 py-1 rounded-lg bg-slate-900 text-amber-200 border border-amber-800/60 font-mono text-[11px]"
                      >
                        + {name}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* SUB-VIEW 3: CONFLICT SYNTHESIZER */}
      {subTab === "resolver" && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          <div className="lg:col-span-5 glass-card p-6 rounded-2xl space-y-4">
            <h3 className="text-base font-bold text-white flex items-center gap-2">
              <Scale className="h-4 w-4 text-indigo-400" />
              <span>Define Competing Norms</span>
            </h3>
            <p className="text-xs text-slate-400">
              When two legitimate cultural values clash (e.g. speed vs quality, autonomy vs alignment), synthesize a hybrid contract.
            </p>

            <form onSubmit={handleResolveConflict} className="space-y-4 text-xs">
              <div>
                <label className="font-mono text-[11px] uppercase tracking-wider text-slate-300 block mb-1">
                  Norm / Expectation A (Side 1)
                </label>
                <textarea
                  rows={2}
                  value={normA}
                  onChange={(e) => setNormA(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700/80 rounded-xl p-2.5 text-slate-200 focus:border-indigo-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="font-mono text-[11px] uppercase tracking-wider text-slate-300 block mb-1">
                  Norm / Expectation B (Side 2)
                </label>
                <textarea
                  rows={2}
                  value={normB}
                  onChange={(e) => setNormB(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700/80 rounded-xl p-2.5 text-slate-200 focus:border-indigo-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="font-mono text-[11px] uppercase tracking-wider text-slate-300 block mb-1">
                  Team Context
                </label>
                <input
                  type="text"
                  value={conflictContext}
                  onChange={(e) => setConflictContext(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700/80 rounded-xl p-2.5 text-slate-200 focus:border-indigo-500 focus:outline-none"
                />
              </div>

              {resolverError && (
                <div className="p-3 rounded-xl bg-rose-950/60 border border-rose-800 text-rose-300">
                  {resolverError}
                </div>
              )}

              <button
                type="submit"
                disabled={resolving}
                className="w-full py-2.5 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-lg shadow-indigo-500/25 transition-all flex items-center justify-center gap-2 disabled:opacity-60"
              >
                {resolving ? (
                  <>
                    <RefreshCw className="h-4 w-4 animate-spin" />
                    <span>Synthesizing Non-Zero-Sum Hybrid...</span>
                  </>
                ) : (
                  <>
                    <Scale className="h-4 w-4" />
                    <span>Synthesize Hybrid Norm</span>
                  </>
                )}
              </button>
            </form>
          </div>

          <div className="lg:col-span-7">
            {conflictResolution ? (
              <div className="glass-card p-6 sm:p-8 rounded-2xl space-y-5 animate-in fade-in duration-200 shadow-xl">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-mono font-semibold px-2.5 py-0.5 rounded-lg bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                    SYNTHESIZED SOLUTION
                  </span>
                </div>

                <h4 className="text-xl font-bold text-white">
                  {conflictResolution.title}
                </h4>

                <p className="text-xs text-slate-300 leading-relaxed bg-slate-950/80 p-3.5 rounded-xl border border-slate-800">
                  <strong className="text-emerald-400">Rationale:</strong> {conflictResolution.synthesisRationale}
                </p>

                {/* The Golden Rule */}
                <div className="p-4 rounded-xl bg-indigo-950/40 border border-indigo-800/50 space-y-1">
                  <span className="text-xs font-mono font-bold uppercase tracking-wider text-indigo-300 block">
                    👑 The Golden Operating Guideline
                  </span>
                  <p className="text-sm font-medium text-white">
                    {conflictResolution.theGoldenRule}
                  </p>
                </div>

                {/* When to lean A vs B */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                  <div className="p-3.5 rounded-xl bg-slate-950/80 border border-slate-800">
                    <span className="font-mono font-bold text-amber-400 block mb-1 uppercase text-[10px]">
                      When to Lean Toward Side A:
                    </span>
                    <p className="text-slate-300 text-[11px]">{conflictResolution.whenToLeanA}</p>
                  </div>

                  <div className="p-3.5 rounded-xl bg-slate-950/80 border border-slate-800">
                    <span className="font-mono font-bold text-indigo-300 block mb-1 uppercase text-[10px]">
                      When to Lean Toward Side B:
                    </span>
                    <p className="text-slate-300 text-[11px]">{conflictResolution.whenToLeanB}</p>
                  </div>
                </div>

                {/* Escalation Protocol */}
                <div className="p-3.5 rounded-xl bg-slate-950/80 border border-slate-800 text-xs">
                  <span className="font-mono font-bold text-emerald-400 block mb-1 uppercase text-[10px]">
                    ⚡ Escalation Protocol (Breaking Ties Without Resentment):
                  </span>
                  <p className="text-slate-300 text-[11px]">{conflictResolution.escalationProtocol}</p>
                </div>
              </div>
            ) : (
              <div className="p-12 text-center rounded-2xl glass-card text-slate-400 space-y-3">
                <Scale className="h-8 w-8 text-indigo-400 mx-auto" />
                <p className="text-sm font-medium text-slate-200">
                  Ready to resolve norm clashes
                </p>
                <p className="text-xs max-w-sm mx-auto text-slate-400">
                  Define two conflicting team expectations on the left to produce a unified operational synthesis.
                </p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* SUB-VIEW 4: LIVE ADVISOR CHAT */}
      {subTab === "advisor" && (
        <div className="glass-card p-6 rounded-2xl flex flex-col h-[600px]">
          <div className="flex items-center justify-between pb-4 border-b border-slate-800">
            <div className="flex items-center gap-2.5">
              <Bot className="h-5 w-5 text-indigo-400" />
              <div>
                <h3 className="text-sm font-bold text-white">
                  Social Systems & Norms Architect Coach
                </h3>
                <span className="text-[11px] text-slate-400">
                  Ask about unwritten rules, team dynamics, reciprocity equations, or remote friction
                </span>
              </div>
            </div>
          </div>

          {/* Messages Stream */}
          <div className="flex-1 overflow-y-auto py-4 space-y-4 pr-1 text-xs">
            {chatMessages.map((msg, idx) => (
              <div
                key={idx}
                className={`flex gap-3 ${msg.role === "user" ? "justify-end" : "justify-start"}`}
              >
                {msg.role === "architect" && (
                  <div className="h-7 w-7 rounded-lg bg-indigo-950/80 border border-indigo-800/80 text-indigo-300 flex items-center justify-center shrink-0 mt-0.5">
                    <Bot className="h-4 w-4" />
                  </div>
                )}
                <div
                  className={`p-3.5 rounded-2xl max-w-xl leading-relaxed ${
                    msg.role === "user"
                      ? "bg-indigo-600 text-white rounded-tr-none shadow-md shadow-indigo-500/20"
                      : "bg-slate-950/90 border border-slate-800 text-slate-200 rounded-tl-none whitespace-pre-line"
                  }`}
                >
                  {msg.content}
                </div>
              </div>
            ))}

            {chatLoading && (
              <div className="flex gap-3 justify-start">
                <div className="h-7 w-7 rounded-lg bg-indigo-950/80 border border-indigo-800/80 text-indigo-300 flex items-center justify-center shrink-0">
                  <RefreshCw className="h-4 w-4 animate-spin" />
                </div>
                <div className="p-3.5 rounded-2xl bg-slate-950/90 border border-slate-800 text-slate-400 text-xs italic">
                  Architect is crafting guidance...
                </div>
              </div>
            )}
          </div>

          {/* Input Form */}
          <form onSubmit={handleSendChatMessage} className="pt-3 border-t border-slate-800 flex gap-2">
            <input
              type="text"
              value={chatInput}
              onChange={(e) => setChatInput(e.target.value)}
              placeholder="e.g. How do we prevent senior devs from being overwhelmed with mentorship requests?"
              className="flex-1 bg-slate-900 border border-slate-700/80 rounded-xl px-4 py-2 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500"
            />
            <button
              type="submit"
              disabled={chatLoading || !chatInput.trim()}
              className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold flex items-center gap-1.5 disabled:opacity-50 transition-colors shadow-md shadow-indigo-500/20"
            >
              <Send className="h-3.5 w-3.5" />
              <span>Send</span>
            </button>
          </form>
        </div>
      )}

    </div>
  );
};
