import React from "react";
import { 
  Building2, 
  MapPin, 
  Mail, 
  Phone, 
  Globe, 
  ShieldCheck, 
  AlertTriangle, 
  CheckCircle2, 
  ExternalLink, 
  Cpu, 
  Sparkles, 
  TrendingUp, 
  FileCode2,
  Calendar,
  Layers,
  ArrowRight,
  Ban,
  Archive,
  Clock,
  Bot
} from "lucide-react";
import { EquipmentListing } from "../types";
import { getEquipmentImageUrl } from "../utils/equipmentImages";
import { 
  getOriginalListingUrl, 
  getOriginalSourceDomain, 
  getLinkHealthBadge, 
  isListingPrunedOrSold 
} from "../utils/sourceLinks";

interface EquipmentCardProps {
  listing: EquipmentListing;
  onSelect: (listing: EquipmentListing) => void;
  onAnalyzeMatch?: (listing: EquipmentListing) => void;
  onDraftContract?: (listing: EquipmentListing) => void;
  onMarkStatus?: (listing: EquipmentListing, status: "Active" | "Sold" | "Delisted" | "Archived") => void;
}

export const EquipmentCard: React.FC<EquipmentCardProps> = ({
  listing,
  onSelect,
  onAnalyzeMatch,
  onDraftContract,
  onMarkStatus,
}) => {
  const isWTB = listing.type === "WTB";
  const hasMatch = Boolean(listing.matchScore && listing.matchScore > 0);
  const imageUrl = getEquipmentImageUrl(listing);
  const sourceUrl = getOriginalListingUrl(listing);
  const sourceDomain = getOriginalSourceDomain(listing);
  const health = getLinkHealthBadge(listing);
  const isPruned = isListingPrunedOrSold(listing);

  return (
    <div
      id={`card-${listing.id}`}
      className={`group relative flex flex-col justify-between overflow-hidden rounded-xl border bg-slate-900/60 shadow-lg backdrop-blur-md transition-all duration-200 hover:bg-slate-900/90 ${
        isPruned 
          ? "border-amber-900/50 opacity-75 hover:opacity-100" 
          : "border-slate-800/80 hover:border-slate-700 hover:shadow-indigo-500/10"
      }`}
    >
      {/* Visual Image Header */}
      <div 
        onClick={() => onSelect(listing)} 
        className="relative h-44 w-full overflow-hidden bg-slate-950 cursor-pointer border-b border-slate-800/80"
      >
        <img
          src={imageUrl}
          alt={`${listing.make} ${listing.model}`}
          referrerPolicy="no-referrer"
          onError={(e) => {
            (e.currentTarget as HTMLImageElement).src = getEquipmentImageUrl({
              category: listing.category,
              make: listing.make,
              model: listing.model,
            });
          }}
          className={`h-full w-full object-cover object-center transition-transform duration-500 group-hover:scale-105 ${
            isPruned ? "grayscale-[60%] opacity-70" : "opacity-90 group-hover:opacity-100"
          }`}
        />
        <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/30 to-transparent" />

        {/* Top Floating Badges */}
        <div className="absolute top-3 left-3 right-3 flex items-start justify-between gap-2">
          <div className="flex flex-col gap-1">
            <span
              className={`rounded-md px-2.5 py-1 text-[11px] font-mono font-bold tracking-wider uppercase backdrop-blur-md shadow-md ${
                isWTB
                  ? "bg-emerald-950/90 text-emerald-300 border border-emerald-500/40"
                  : "bg-cyan-950/90 text-cyan-300 border border-cyan-500/40"
              }`}
            >
              {isWTB ? "● WTB (DEMAND)" : "● WTS (SUPPLY)"}
            </span>

            {/* Auto Generated Badge */}
            {listing.isAutoGenerated !== false && (
              <span className="inline-flex items-center gap-1 rounded bg-purple-950/90 border border-purple-500/40 px-2 py-0.5 text-[10px] font-mono font-bold text-purple-300 backdrop-blur-md shadow-sm">
                <Bot className="h-3 w-3 text-purple-400" />
                <span>AUTO GENERATED</span>
              </span>
            )}

            {/* Health / Sold Badge */}
            {isPruned && (
              <span className={`inline-flex items-center gap-1 rounded px-2 py-0.5 text-[10px] font-mono font-bold border backdrop-blur-md ${health.badgeClass}`}>
                <span className={`h-1.5 w-1.5 rounded-full ${health.dotClass}`} />
                {health.label}
              </span>
            )}
          </div>

          <div className="flex flex-col items-end gap-1">
            {hasMatch && !isPruned && (
              <div className="flex items-center gap-1 rounded-full border border-amber-500/50 bg-amber-950/90 px-2.5 py-1 text-xs font-mono font-bold text-amber-300 shadow-md backdrop-blur-md">
                <Sparkles className="h-3.5 w-3.5 text-amber-400 animate-pulse" />
                <span>{listing.matchScore}% MATCH</span>
              </div>
            )}
            
            {/* Direct Source Badge on Header */}
            <a
              href={sourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
              className="flex items-center gap-1 rounded bg-slate-950/85 px-2 py-0.5 text-[10px] font-mono text-cyan-300 hover:text-white border border-slate-800 hover:border-cyan-500/50 backdrop-blur-md transition-colors"
              title={`View Original Listing on ${sourceDomain}`}
            >
              <span>{sourceDomain}</span>
              <ExternalLink className="h-2.5 w-2.5" />
            </a>
          </div>
        </div>

        {/* Bottom Category Tag over image */}
        <div className="absolute bottom-2.5 left-3 right-3 flex items-center justify-between text-xs">
          <span className="rounded-md border border-slate-700/70 bg-slate-900/90 px-2 py-0.5 text-[10px] font-medium text-slate-200 backdrop-blur-md">
            {listing.category}
          </span>
          {listing.condition && (
            <span className="rounded border border-slate-700/70 bg-slate-900/90 px-2 py-0.5 font-mono text-[10px] text-slate-300 backdrop-blur-md">
              {listing.condition}
            </span>
          )}
        </div>
      </div>

      {/* Main Content Body */}
      <div className="p-5">
        {/* Pruned Notice if sold */}
        {listing.prunedReason && (
          <div className="mb-3 rounded border border-amber-500/30 bg-amber-950/40 p-2 text-xs text-amber-300 flex items-center gap-1.5 font-mono">
            <AlertTriangle className="h-3.5 w-3.5 shrink-0 text-amber-400" />
            <span>Audit Flag: {listing.prunedReason}</span>
          </div>
        )}

        {/* Title & Make/Model */}
        <div className="cursor-pointer" onClick={() => onSelect(listing)}>
          <h3 className={`text-base font-semibold leading-snug transition-colors group-hover:text-cyan-300 line-clamp-1 ${isPruned ? 'text-slate-300 line-through' : 'text-white'}`}>
            {listing.title}
          </h3>
          <div className="mt-1 flex items-center gap-2 font-mono text-xs text-slate-400">
            <span>Make: <strong className="text-slate-200">{listing.make}</strong></span>
            <span>•</span>
            <span>Model: <strong className="text-slate-200">{listing.model}</strong></span>
            {listing.year && (
              <>
                <span>•</span>
                <span className="text-slate-400">{listing.year}</span>
              </>
            )}
          </div>
        </div>

        {/* Pricing / Valuation Block */}
        <div className="mt-4 rounded-lg border border-slate-800/80 bg-slate-950/60 p-3">
          <div className="flex items-baseline justify-between">
            <div>
              <span className="text-[11px] font-mono uppercase text-slate-400">
                {isWTB ? "Max Target Budget" : "Asking / Sourced Price"}
              </span>
              <div className="text-xl font-bold font-mono text-white">
                ${(listing.priceTarget ?? 0).toLocaleString()}{" "}
                <span className="text-xs font-normal text-slate-400">{listing.currency || "USD"}</span>
              </div>
            </div>

            <div className="text-right">
              <span className="text-[11px] font-mono uppercase text-slate-400">Market Comps Avg</span>
              <div className="text-sm font-semibold font-mono text-slate-300">
                ${(listing.marketCompAverage ?? 0).toLocaleString()}
              </div>
            </div>
          </div>

          {listing.marginSpreadEstimate && listing.marginSpreadEstimate > 0 && !isPruned && (
            <div className="mt-2 flex items-center justify-between border-t border-slate-800/60 pt-2 text-xs font-mono text-emerald-400">
              <span className="flex items-center gap-1">
                <TrendingUp className="h-3.5 w-3.5" />
                Est. Arbitrage / Spread:
              </span>
              <span className="font-bold">+${(listing.marginSpreadEstimate ?? 0).toLocaleString()}</span>
            </div>
          )}
        </div>

        {/* Technical Specs Pills */}
        <div className="mt-3">
          <div className="text-[11px] font-mono text-slate-400 mb-1.5 uppercase">Key Specs:</div>
          <div className="flex flex-wrap gap-1.5">
            {Object.entries(listing.specs).slice(0, 3).map(([key, val]) => (
              <div
                key={key}
                className="rounded border border-slate-800 bg-slate-900/80 px-2 py-1 font-mono text-[11px] text-slate-300"
              >
                <span className="text-slate-500">{key}: </span>
                <span className="text-cyan-300 font-medium">{val}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Inferred Contact & Entity Card with Original Source Link */}
        <div className="mt-4 rounded-lg border border-slate-800 bg-slate-950/80 p-3 text-xs">
          <div className="flex items-center justify-between border-b border-slate-800/70 pb-2">
            <div className="flex items-center gap-1.5 font-semibold text-slate-200">
              <Building2 className="h-3.5 w-3.5 text-indigo-400" />
              <span className="truncate max-w-[170px]">{listing.contact.entityName}</span>
            </div>
            
            {/* Inference Confidence Badge */}
            <div className="flex items-center gap-1">
              <span
                className={`rounded px-1.5 py-0.5 font-mono text-[10px] font-bold ${
                  listing.contact.inferenceConfidence >= 90
                    ? "bg-emerald-500/15 text-emerald-400 border border-emerald-500/30"
                    : "bg-amber-500/15 text-amber-400 border border-amber-500/30"
                }`}
                title={`Inferred via: ${listing.contact.inferenceMethod}`}
              >
                {listing.contact.inferenceConfidence}% INFERRED
              </span>
            </div>
          </div>

          <div className="mt-2 space-y-1 text-slate-400 font-mono text-[11px]">
            {listing.contact.contactPerson && (
              <div className="text-slate-300 truncate">
                Contact: <strong className="text-white font-sans">{listing.contact.contactPerson}</strong>
              </div>
            )}
            
            <div className="flex items-center gap-3 text-slate-400">
              {listing.contact.location && (
                <div className="flex items-center gap-1 truncate">
                  <MapPin className="h-3 w-3 text-slate-500 shrink-0" />
                  <span className="truncate">{listing.contact.location}</span>
                </div>
              )}
            </div>

            {/* Direct Clickable Source Link Row */}
            <div className="flex items-center justify-between pt-1 text-[11px]">
              <a
                href={sourceUrl}
                target="_blank"
                rel="noopener noreferrer"
                onClick={(e) => e.stopPropagation()}
                className="flex items-center gap-1 text-cyan-400 hover:text-cyan-300 hover:underline font-mono"
              >
                <Globe className="h-3 w-3 text-cyan-500" />
                <span className="truncate max-w-[140px]">{sourceDomain}</span>
                <ExternalLink className="h-2.5 w-2.5" />
              </a>
              <span className="rounded bg-slate-800 px-1 text-slate-400 font-mono text-[10px]">
                {listing.contact.inferenceMethod}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Action Footer */}
      <div className="mt-5 flex items-center justify-between gap-2 border-t border-slate-800/80 p-4 pt-3 bg-slate-950/40">
        <div className="flex items-center gap-1.5">
          <button
            id={`btn-view-${listing.id}`}
            onClick={() => onSelect(listing)}
            className="flex items-center gap-1 rounded-md border border-slate-700 bg-slate-800/60 px-3 py-1.5 text-xs font-medium text-slate-200 transition-all hover:bg-slate-700 hover:text-white"
          >
            <span>Specs & Comps</span>
            <ArrowRight className="h-3 w-3" />
          </button>
          
          <a
            href={sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            onClick={(e) => e.stopPropagation()}
            className="flex items-center gap-1 rounded-md border border-slate-800 bg-slate-900/80 px-2 py-1.5 text-xs font-mono text-cyan-400 hover:border-cyan-500/50 hover:bg-slate-800 transition-all"
            title="Open original listing URL in new tab"
          >
            <ExternalLink className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Source</span>
          </a>
        </div>

        {hasMatch && !isPruned ? (
          <button
            id={`btn-match-${listing.id}`}
            onClick={() => onAnalyzeMatch?.(listing)}
            className="flex items-center gap-1.5 rounded-md bg-gradient-to-r from-amber-500 to-emerald-500 px-3 py-1.5 text-xs font-semibold text-slate-950 shadow-md transition-all hover:brightness-110 active:scale-95"
          >
            <Sparkles className="h-3.5 w-3.5" />
            <span>Match & Contract</span>
          </button>
        ) : (
          <button
            id={`btn-scour-match-${listing.id}`}
            onClick={() => onAnalyzeMatch?.(listing)}
            className="flex items-center gap-1 rounded-md border border-indigo-500/30 bg-indigo-500/10 px-2.5 py-1.5 text-xs font-medium text-indigo-300 transition-all hover:bg-indigo-500/20"
          >
            <Sparkles className="h-3 w-3 text-indigo-400" />
            <span>Match</span>
          </button>
        )}
      </div>
    </div>
  );
};

