import React, { useState } from "react";
import { Norm, NormComment } from "../types";
import { 
  X, 
  ThumbsUp, 
  Copy, 
  Share2, 
  Check, 
  Plus, 
  AlertTriangle, 
  ShieldCheck, 
  Zap, 
  Globe, 
  Calendar, 
  MessageSquare, 
  Send,
  User,
  Sparkles,
  BookMarked,
  Bot
} from "lucide-react";

interface NormDetailModalProps {
  norm: Norm | null;
  onClose: () => void;
  isInCharter: boolean;
  onToggleCharter: (norm: Norm) => void;
  onVote: (normId: string) => void;
  onAddComment: (normId: string, commentText: string, authorName: string) => void;
}

export const NormDetailModal: React.FC<NormDetailModalProps> = ({
  norm,
  onClose,
  isInCharter,
  onToggleCharter,
  onVote,
  onAddComment,
}) => {
  if (!norm) return null;

  const [commentInput, setCommentInput] = useState("");
  const [authorName, setAuthorName] = useState("");
  const [copiedSlack, setCopiedSlack] = useState(false);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);

  const copySlack = () => {
    const text = `📋 *Team Operating Norm: ${norm.title}*\n\n⚡ *Trigger:* ${norm.triggerSituation}\n📜 *Explicit Rule:* ${norm.explicitRule}\n🛡️ *Violation Remedy:* ${norm.violationRemedy}\n📊 *Reciprocity Rating:* ${norm.reciprocityIndex}% | *Clarity:* ${norm.clarityScore}%\n\n_Adopted via NormsExchange_`;
    navigator.clipboard.writeText(text);
    setCopiedSlack(true);
    setTimeout(() => setCopiedSlack(false), 2000);
  };

  const copyMarkdown = () => {
    const md = `### ${norm.title}\n**Category**: ${norm.category} | **Reciprocity Index**: ${norm.reciprocityIndex}%\n\n> ${norm.tagline}\n\n- **When (Trigger)**: ${norm.triggerSituation}\n- **What (Explicit Rule)**: ${norm.explicitRule}\n- **If Violated (Remedy)**: ${norm.violationRemedy}\n- **Anti-Patterns Prevented**: ${norm.antiPatterns?.join(", ") || "None"}\n`;
    navigator.clipboard.writeText(md);
    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2000);
  };

  const handleSubmitComment = (e: React.FormEvent) => {
    e.preventDefault();
    if (!commentInput.trim()) return;
    onAddComment(norm.id, commentInput.trim(), authorName.trim() || "Anonymous Collaborator");
    setCommentInput("");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-200">
      <div 
        className="glass rounded-2xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden text-slate-100 border border-slate-800"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-6 border-b border-slate-800 flex items-start justify-between gap-4 bg-slate-950/80">
          <div>
            <div className="flex flex-wrap items-center gap-2 mb-2">
              <span className="text-xs font-mono font-semibold px-2.5 py-0.5 rounded-lg bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                {norm.category}
              </span>
              {norm.isAutoGenerated !== false && (
                <span className="inline-flex items-center gap-1 text-xs font-mono font-bold px-2.5 py-0.5 rounded-lg bg-purple-950/80 text-purple-300 border border-purple-500/40">
                  <Bot className="h-3.5 w-3.5 text-purple-400" />
                  <span>⚡ AUTO GENERATED</span>
                </span>
              )}
              <span className="text-xs font-mono font-bold px-2.5 py-0.5 rounded-lg bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                {norm.reciprocityIndex}% Equity
              </span>
              <span className="text-xs font-mono text-slate-400">
                {norm.adoptionWeeks}w adoption ramp
              </span>
            </div>
            <h2 className="text-xl sm:text-2xl font-bold text-white">
              {norm.title}
            </h2>
            <p className="text-xs sm:text-sm text-slate-300 mt-1">
              {norm.tagline}
            </p>
          </div>

          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-white hover:bg-slate-800/80 rounded-xl transition-colors shrink-0"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Modal Scrollable Body */}
        <div className="p-6 overflow-y-auto space-y-6 flex-1 text-sm">
          
          {/* Executive Overview */}
          <div>
            <h4 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-400 mb-1.5">
              SYSTEM CONTEXT & RATIONALE
            </h4>
            <p className="text-xs sm:text-sm text-slate-300 leading-relaxed bg-slate-950/80 p-4 rounded-xl border border-slate-800/80">
              {norm.description}
            </p>
          </div>

          {/* Explicit Operational Playbook */}
          <div className="space-y-3">
            <h4 className="text-xs font-mono font-bold uppercase tracking-wider text-amber-400">
              THE OPERATIONAL CONTRACT
            </h4>

            <div className="grid grid-cols-1 gap-3">
              {/* Trigger */}
              <div className="p-4 rounded-xl bg-amber-950/20 border border-amber-900/40 text-xs">
                <div className="flex items-center gap-2 text-amber-300 font-bold mb-1">
                  <Zap className="h-4 w-4 text-amber-400" />
                  <span className="font-mono text-[11px] uppercase tracking-wider">The Trigger Situation</span>
                </div>
                <p className="text-slate-200 leading-relaxed text-xs sm:text-sm">
                  {norm.triggerSituation}
                </p>
              </div>

              {/* Explicit Rule */}
              <div className="p-4 rounded-xl bg-indigo-950/30 border border-indigo-900/50 text-xs">
                <div className="flex items-center gap-2 text-indigo-300 font-bold mb-1">
                  <ShieldCheck className="h-4 w-4 text-indigo-400" />
                  <span className="font-mono text-[11px] uppercase tracking-wider">The Explicit Behavioral Contract</span>
                </div>
                <p className="text-white font-medium leading-relaxed text-xs sm:text-sm">
                  {norm.explicitRule}
                </p>
              </div>

              {/* Remedy */}
              <div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-900/40 text-xs">
                <div className="flex items-center gap-2 text-emerald-300 font-bold mb-1">
                  <Check className="h-4 w-4 text-emerald-400" />
                  <span className="font-mono text-[11px] uppercase tracking-wider">Blameless Remedy & Reset</span>
                </div>
                <p className="text-slate-200 leading-relaxed text-xs sm:text-sm">
                  {norm.violationRemedy}
                </p>
              </div>
            </div>
          </div>

          {/* Anti-Patterns & Cultural Context */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 rounded-xl bg-rose-950/20 border border-rose-900/30">
              <span className="text-xs font-mono font-bold uppercase tracking-wider text-rose-400 block mb-2">
                🚫 Anti-Patterns Eliminated
              </span>
              <ul className="space-y-1.5 text-xs text-slate-300">
                {norm.antiPatterns.map((ap, i) => (
                  <li key={i} className="flex items-start gap-1.5">
                    <span className="text-rose-400 font-bold">•</span>
                    <span>{ap}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="p-4 rounded-xl bg-slate-950/80 border border-slate-800">
              <span className="text-xs font-mono font-bold uppercase tracking-wider text-indigo-400 block mb-2">
                🌍 Cross-Cultural Dynamics
              </span>
              <p className="text-xs text-slate-300 leading-relaxed">
                {norm.culturalContextNotes || "Standardized universal operating pattern across asynchronous and co-located team environments."}
              </p>
            </div>
          </div>

          {/* Author info */}
          <div className="flex items-center justify-between p-4 rounded-xl bg-slate-950/80 border border-slate-800">
            <div className="flex items-center gap-3">
              <img 
                src={norm.author.avatar} 
                alt={norm.author.name} 
                className="h-10 w-10 rounded-full object-cover border border-slate-700" 
                referrerPolicy="no-referrer"
              />
              <div>
                <span className="text-xs font-semibold text-white block">
                  Minted by {norm.author.name}
                </span>
                <span className="text-[11px] text-slate-400">
                  {norm.author.role} • {norm.author.organization || "NormsExchange Community"}
                </span>
              </div>
            </div>
            <div className="text-right">
              <span className="text-xs font-mono font-bold text-emerald-400 block">
                {(norm.adoptionsCount ?? 0).toLocaleString()} Adoptions
              </span>
              <span className="text-[11px] font-mono text-slate-500">
                {norm.votesCount} Upvotes
              </span>
            </div>
          </div>

          {/* Community Reflections & Peer Experiences */}
          <div className="pt-2 border-t border-slate-800/80 space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <MessageSquare className="h-4 w-4 text-indigo-400" />
                <h4 className="font-semibold text-white text-xs sm:text-sm">
                  Team Experiences & Adaptations ({norm.comments?.length || 0})
                </h4>
              </div>
            </div>

            {/* Comment List */}
            <div className="space-y-3 max-h-48 overflow-y-auto pr-1">
              {norm.comments && norm.comments.length > 0 ? (
                norm.comments.map((c) => (
                  <div key={c.id} className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 text-xs">
                    <div className="flex items-center justify-between mb-1">
                      <span className="font-semibold text-slate-200">{c.author}</span>
                      <span className="text-[10px] font-mono text-slate-500">{c.timestamp}</span>
                    </div>
                    <p className="text-slate-400 leading-relaxed text-[11px]">{c.content}</p>
                  </div>
                ))
              ) : (
                <p className="text-xs text-slate-500 italic">
                  No peer notes yet. Be the first to share how this norm performed in your team!
                </p>
              )}
            </div>

            {/* Post Comment Form */}
            <form onSubmit={handleSubmitComment} className="flex gap-2">
              <input
                type="text"
                placeholder="Your Name / Role (optional)"
                value={authorName}
                onChange={(e) => setAuthorName(e.target.value)}
                className="w-1/3 bg-slate-900 border border-slate-700/80 rounded-xl px-3 py-2 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-indigo-500"
              />
              <input
                type="text"
                placeholder="Share advice or team adoption nuances..."
                value={commentInput}
                onChange={(e) => setCommentInput(e.target.value)}
                className="flex-1 bg-slate-900 border border-slate-700/80 rounded-xl px-3 py-2 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-indigo-500"
              />
              <button
                type="submit"
                className="px-3.5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold flex items-center gap-1 shadow-md shadow-indigo-500/20"
              >
                <Send className="h-3.5 w-3.5" />
              </button>
            </form>
          </div>

        </div>

        {/* Modal Footer Controls */}
        <div className="p-4 bg-slate-950/90 border-t border-slate-800 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <button
              onClick={copySlack}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-850 bg-slate-800/80 hover:bg-slate-800 text-slate-200 text-xs font-medium border border-slate-700/80 transition-colors"
            >
              <Copy className="h-3.5 w-3.5 text-indigo-400" />
              <span>{copiedSlack ? "Copied Slack!" : "Copy for Slack"}</span>
            </button>

            <button
              onClick={copyMarkdown}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-800/80 hover:bg-slate-800 text-slate-200 text-xs font-medium border border-slate-700/80 transition-colors"
            >
              <BookMarked className="h-3.5 w-3.5 text-emerald-400" />
              <span>{copiedMarkdown ? "Copied Markdown!" : "Copy Markdown"}</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => onVote(norm.id)}
              className={`flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-medium transition-colors ${
                norm.userVoted
                  ? "bg-amber-500/20 text-amber-300 border border-amber-500/40"
                  : "bg-slate-800/80 hover:bg-slate-800 text-slate-300 border border-slate-700/80"
              }`}
            >
              <ThumbsUp className={`h-3.5 w-3.5 ${norm.userVoted ? "fill-amber-300" : ""}`} />
              <span>Upvote ({norm.votesCount})</span>
            </button>

            <button
              onClick={() => onToggleCharter(norm)}
              className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                isInCharter
                  ? "bg-rose-950/80 text-rose-300 hover:bg-rose-900 border border-rose-800 shadow-md shadow-rose-950/40"
                  : "bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg shadow-indigo-500/25"
              }`}
            >
              {isInCharter ? (
                <>
                  <X className="h-3.5 w-3.5" />
                  <span>Remove from Charter</span>
                </>
              ) : (
                <>
                  <Plus className="h-3.5 w-3.5" />
                  <span>Adopt into Team Charter</span>
                </>
              )}
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};

