export type ListingType = "WTB" | "WTS" | "MATCH";

export type EquipmentCategory =
  | "All"
  // Film Equipment Scope (Permanent Mission v1.0.0)
  | "Cameras & Systems"
  | "Lenses & Optics"
  | "Lighting & Grip"
  | "Professional Audio"
  | "Monitoring & Wireless"
  | "Power, Media & Support"
  | "Post & Specialty Film Gear"
  // Legacy / Industrial Scope
  | "Precision Optics & Lasers"
  | "Semiconductor & Cleanroom"
  | "Industrial CNC & Machining"
  | "Lab & Metrology Testing"
  | "High-Voltage & Power Systems"
  | "Automation & Robotics"
  | "Aerospace & Avionics Surplus";

export type TradeCorridor = 
  | "ALL"
  | "LA_TO_VN"      // Los Angeles ➔ Vietnam
  | "VN_TO_US"      // Vietnam ➔ United States
  | "DOMESTIC_US"   // Intra-US (LA, NY, Atlanta, etc.)
  | "DOMESTIC_VN"   // Intra-Vietnam (HCMC, Hanoi, Da Nang)
  | "GLOBAL";       // Worldwide / Multi-region

export type SourceCorridor = TradeCorridor;


export type ConditionGrade = 
  | "New / Unopened (NOS)"
  | "Refurbished / Calibrated"
  | "Working / Tested"
  | "Untested / As-Is"
  | "Parts / Core";

export interface InferredContact {
  entityName: string;
  contactPerson?: string;
  email?: string;
  phone?: string;
  location: string;
  sourceDomain: string;
  sourceUrl: string;
  inferenceConfidence: number; // 0 - 100%
  inferenceMethod: "Direct Web Crawl" | "Whois / Registry" | "Listing Footer Regex" | "PDF Spec Sheet / Invoice" | "Entity Resolution Model";
  verifiedStatus: "Verified" | "High Confidence" | "Needs Confirmation";
  notes?: string;
}

export interface MarketComp {
  source: string;
  date: string;
  price: number;
  condition: string;
  url?: string;
}

export interface EquipmentListing {
  id: string;
  type: ListingType;
  title: string;
  category: Exclude<EquipmentCategory, "All">;
  make: string;
  model: string;
  year?: number;
  partNumber?: string;
  serialNumber?: string;
  priceTarget: number; // Target price for WTB or Asking price for WTS
  currency: string;
  marketCompAverage: number;
  condition: ConditionGrade;
  specs: Record<string, string>;
  description: string;
  urgencyOrAvailability: "Immediate" | "Within 14 Days" | "30+ Days" | "Flexible";
  contact: InferredContact;
  tags: string[];
  discoveredAt: string;
  lastVerifiedAt: string;
  matchScore?: number; // Calculated match percentage if matched
  matchedWithId?: string;
  marginSpreadEstimate?: number;
  status: "Active" | "Matched" | "Indexed" | "Dispatched to Shopify" | "Archived" | "Sold" | "Delisted";
  githubIndexRef?: string;
  imageUrl?: string;
  sourceUrl?: string;
  linkHealth?: "Live / Verified" | "Sold / Ended" | "404 Not Found" | "Pending Audit";
  prunedReason?: string;
  isAutoGenerated?: boolean; // Required flag per AGENTS.md transparency rule
  verificationCount?: number; // Strict requirement: must be >= 1 for Codex outbox dispatch
  strictVerification?: boolean; // Enforces the Golden Rule: Zero mock data/hallucination
  generationMethod?: "Autonomous Crawler" | "Gemini Entity Extraction" | "Benchmark Seed" | "Manual Entry" | "Market Comp Engine";
}

export interface PruneAuditItem {
  id: string;
  title: string;
  make: string;
  model: string;
  sourceUrl: string;
  sourceDomain: string;
  reason: "Marked Sold" | "Origin Delisted (404)" | "Out of Stock" | "Stale Listing TTL Expired" | "Manual Prune";
  actionTaken: "Archived (Soft Prune)" | "Purged (Hard Delete)";
  status: string;
  timestamp: string;
}

export interface PruneAuditReport {
  timestamp: string;
  totalExamined: number;
  activeCount: number;
  prunedCount: number;
  soldCount: number;
  delistedCount: number;
  mode: "archive" | "purge";
  items: PruneAuditItem[];
}

/* =========================================================
   NX CONTRACT V0.2.0 SCHEMAS & BATCH TYPES
   ========================================================= */

export interface SourcingContractCandidate {
  candidate_id: string;
  category: string;
  equipment_make: string;
  equipment_model: string;
  target_price_usd: number;
  stated_currency: string;
  stated_price_amount: number;
  condition_stated: string;
  origin_location: string;
  delivery_target_location: string;
  corridor: string;
  evidence: {
    source_url: string;
    source_domain: string;
    source_language: "en" | "vi" | "de" | "fr" | "ja";
    observation_timestamp: string;
    raw_excerpt: string;
    contact_entity: string;
  };
  arbitrage_spread_usd?: number;
}

export interface WTBCandidateBatch {
  batch_id: string;
  contract_version: "0.2.0";
  intake_version: "0.1.0";
  created_at: string;
  corridor: string;
  role: string;
  candidates_count: number;
  total_arbitrage_spread_usd: number;
  candidates: SourcingContractCandidate[];
  sha256_digest?: string;
}

export interface WTBRequest {
  id: string;
  buyerOrganization: string;
  targetMake: string;
  targetModel: string;
  maxBudget: number;
  currency: string;
  conditionAcceptance: ConditionGrade[];
  urgency: "Immediate / Mission Critical" | "Standard (14 Days)" | "Flexible";
  requiredSpecs: string[];
  matchedListingsCount: number;
  createdAt: string;
  status: "Open Demand" | "Sourcing In Progress" | "Candidates Found" | "Fulfilled";
}

export interface SourcingScanResult {
  query: string;
  timestamp: string;
  foundCount: number;
  items: EquipmentListing[];
  inferredContactsCount: number;
  summaryNote: string;
}

export interface SiteIndexTestResult {
  url: string;
  domain: string;
  fetchMethod: "DIRECT_BROWSER_FETCH" | "ANTI_BOT_SEARCH_GROUNDED" | "TIER3_EXTRACTOR";
  httpStatus: number;
  botBlocked: boolean;
  blockReason?: string;
  bypassSuccessful: boolean;
  extractedCount: number;
  extractedItems: EquipmentListing[];
  rawSummary: string;
  timestamp: string;
}

export interface GoalMilestone {
  id: string;
  title: string;
  completed: boolean;
  targetValue?: string;
}

export interface AgentGoal {
  id: string;
  title: string;
  category: "Site Indexing & Sourcing" | "Market Arbitrage" | "Outbox & Codex" | "Hygiene & Audit" | "Operating Charters";
  description: string;
  targetCount: number;
  currentCount: number;
  unit: string;
  progress: number;
  status: "IN_PROGRESS" | "COMPLETED" | "PAUSED";
  priority: "CRITICAL" | "HIGH" | "MEDIUM";
  corridor?: TradeCorridor;
  actionLabel?: string;
  actionType?: "INDEX_SWEEP" | "ARBITRAGE_EVAL" | "OUTBOX_DISPATCH" | "PRUNE_DATABASE" | "CUSTOM";
  milestones: GoalMilestone[];
  lastExecutedAt?: string;
}

export interface MarketDepthItem {
  id: string;
  item: string;
  category: string;
  bidPrice: number; // Highest WTB
  askPrice: number; // Lowest WTS
  spread: number;
  spreadPercent: number;
  wtbVolume: number;
  wtsVolume: number;
  liquidityTier: "High" | "Medium" | "Low";
}

/* =========================================================
   NORMS ARCHITECTURE & CHARTER TYPES
   ========================================================= */

export type NormCategory =
  | "All"
  | "Communication"
  | "Engineering"
  | "Reciprocity & Social"
  | "Meetings & Time"
  | "Decision Making"
  | "Cross-Cultural"
  | "Trade & Compliance"
  | "Leadership";

export interface NormComment {
  id: string;
  author: string;
  avatar: string;
  role: string;
  content: string;
  timestamp: string;
  likes: number;
}

export interface Norm {
  id: string;
  title: string;
  category: Exclude<NormCategory, "All">;
  tagline: string;
  description: string;
  triggerSituation: string;
  explicitRule: string;
  violationRemedy: string;
  reciprocityIndex: number;
  frictionRisk: "Low" | "Medium" | "High";
  clarityScore: number;
  antiPatterns: string[];
  adoptionWeeks: number;
  culturalContextNotes?: string;
  votesCount: number;
  adoptionsCount: number;
  tags: string[];
  author: {
    name: string;
    role: string;
    avatar: string;
    organization?: string;
  };
  comments?: NormComment[];
  isCustom?: boolean;
  isAutoGenerated?: boolean;
  generationMethod?: string;
  userVoted?: boolean;
  userSaved?: boolean;
}

export interface CharterMemberVote {
  id: string;
  memberName: string;
  role: string;
  avatar: string;
  status: "approved" | "nuanced" | "blocked";
  comment?: string;
  votedAt: string;
}

export interface TeamCharter {
  id: string;
  title: string;
  teamName: string;
  description: string;
  norms: Norm[];
  createdAt: string;
  updatedAt: string;
  members: CharterMemberVote[];
}

export interface AuditResult {
  overallHealthScore: number;
  clarityScore: number;
  reciprocityScore: number;
  psychologicalSafetyScore: number;
  strengths: string[];
  criticalFrictionPoints: Array<{
    risk: string;
    impact: "High" | "Medium" | "Low";
    unwrittenAssumption: string;
    recommendedPatch: string;
  }>;
  missingCrucialNorms: string[];
  executiveSummary: string;
}

export interface ConflictResolution {
  title: string;
  synthesisRationale: string;
  theGoldenRule: string;
  whenToLeanA: string;
  whenToLeanB: string;
  escalationProtocol: string;
}

export interface SocialExchangeScenario {
  id: string;
  title: string;
  context: string;
  actorA: string;
  actorB: string;
  choiceOptions: {
    id: string;
    action: string;
    outcomeText: string;
    equityImpactA: number;
    equityImpactB: number;
    relationshipTrustChange: number;
    socialTheoryPrinciple: string;
  }[];
}

/* =========================================================
   INDEXED SOURCES REGISTRY & RATE-METERING TYPES
   ========================================================= */

export type SourceAccessMethod = 
  | "Public REST API"
  | "Partner / Authenticated API"
  | "Structured Web Scraper"
  | "RSS / XML Feed"
  | "GraphQL Endpoint"
  | "Manual Curator Intake";

export type SourceHealthStatus = 
  | "Operational / Up"
  | "Degraded / Slow"
  | "Rate Limited / Cooling Down"
  | "Down / Error"
  | "Maintenance"
  | "Paused by Admin";

export type SourceRobotsPolicy = 
  | "Allowed with Respect"
  | "Restricted Paths"
  | "Disallowed / API Only"
  | "Custom User-Agent Required";

export type SourceTier = 
  | "Tier 1 - Primary Direct"
  | "Tier 2 - Verified Broker"
  | "Tier 3 - Secondary Exchange"
  | "Tier 4 - Community Forum";

export interface SourceSelectors {
  title?: string;
  price?: string;
  currency?: string;
  make?: string;
  model?: string;
  condition?: string;
  location?: string;
  sellerName?: string;
  images?: string;
  listingUrl?: string;
}

export interface ListingSource {
  id: string;
  name: string;
  domain: string;
  baseUrl: string;
  catalogUrl?: string;
  tier: SourceTier;
  corridor: TradeCorridor;
  categoryFocus: EquipmentCategory[];
  description: string;
  
  // Spidering & Robots Compliance
  spideringAllowed: boolean;
  robotsTxtUrl?: string;
  robotsTxtStatus: SourceRobotsPolicy;
  allowedPaths: string[];
  disallowedPaths: string[];
  userAgentPolicy: string;
  crawlDelaySeconds?: number;
  
  // Access Rules & API
  accessMethod: SourceAccessMethod;
  accessRulesSummary: string;
  authRequired: boolean;
  authType: "None / Open" | "API Key (Header)" | "Bearer Token / OAuth2" | "Basic Auth" | "Session Cookie";
  hasPublicApi: boolean;
  apiEndpoint?: string;
  apiDocsUrl?: string;
  apiAccessRules?: string;

  // Rate Limiting & Metering
  maxRequestsPerHour: number | null;
  burstLimit: number | null;
  throttleDelayMs: number | null;
  requestsThisHour: number;
  totalLifetimeRequests: number;
  lastRequestTimestamp?: string;
  hourlyQuotaResetAt?: string;

  // Health & Monitoring
  healthStatus: SourceHealthStatus;
  lastCheckedAt?: string;
  lastLatencyMs?: number;
  uptimePercent: number;
  httpStatusCode?: number;
  consecutiveErrors?: number;
  lastErrorMessage?: string;

  // Scraping Selectors & Headers
  selectors?: SourceSelectors;
  customHeaders?: Record<string, string>;

  // Transparency & Storage
  isAutoGenerated?: boolean;
  generationMethod?: string;
  githubStoragePath?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SourceProbeResult {
  sourceId: string;
  domain: string;
  testedUrl: string;
  timestamp: string;
  success: boolean;
  httpStatus: number;
  latencyMs: number;
  healthStatus: SourceHealthStatus;
  requestsThisHour: number;
  maxRequestsPerHour: number | null;
  quotaRemaining: number | null;
  headers?: Record<string, string>;
  message: string;
}

export interface SourcesApiResponse {
  total: number;
  operationalCount: number;
  totalRequestsThisHour: number;
  maxHourlyQuotaSum: number;
  quotaUtilizationPercent: number;
  avgLatencyMs: number;
  sources: ListingSource[];
}

export interface SourceProbeBatchResponse {
  success: boolean;
  totalProbed: number;
  results: SourceProbeResult[];
  sources: ListingSource[];
}


